sesman/verify_user.c
=> sesman: fix so shadow accounts aren't incorrectly classified "inactive"

sesman/chansrv/chansrv.c
It is rare to happen, but it is a possible.
=> fix possible segfault in chansrv if DISPLAY is not set

common/os_calls.c
It turned out FreeBSD and OS X is special about getsockopt() call.
OpenBSD, NetBSD is almost as same as Linux and the original code will work on them.
=> common: workaround for #146

.gitignore
They're generated during the build.
=> add compile and xrdp-xcon to .gitignore

configure.ac, instfiles/Makefile.am, instfiles/rc.d/Makefile.am, instfiles/rc.d/xrdp
- merge rc script from FreeBSD
- modify Makefile.am to detect OS and install suitable files
=> instfiles: merge rc script from FreeBSD

common/Makefile.am, instfiles/Makefile.am, libxrdp/Makefile.am, sesman/chansrv/Makefile.am, xrdp/Makefile.am
this is required when using make dist to generate a tarball
=> add missing files into extra_dist, this is required when using make dist to generate a tarball

instfiles/xrdp-sesman.service, instfiles/xrdp.service
* Add default directory for debian and set them optional
* Remove the --nodaemon which makes the service fail at start
=> some fixes for systemd on debian

instfiles/rc.d/xrdp
Pointed out by @mirabilos at #232.
=> instfiles: show license at the script taken from FreeBSD ports

common/file.c, common/os_calls.c, instfiles/init.d/xrdp, libxrdp/libxrdp.c, libxrdp/libxrdp.h, libxrdp/xrdp_channel.c, libxrdp/xrdp_jpeg_compress.c, libxrdp/xrdp_mcs.c, libxrdp/xrdp_orders.c, rdp/rdp_mcs.c, rdp/rdp_orders.c, readme.txt, sesman/chansrv/clipboard.c, sesman/chansrv/clipboard_file.c, sesman/chansrv/pulse/module-xrdp-sink.c, sesman/chansrv/pulse/module-xrdp-source.c, sesman/sessvc/sessvc.c, tests/gtcp_proxy/gtcp-proxy.c, tests/tcp_proxy/main.c, vnc/vnc.c, xorg/X11R7.6/rdp/rdpPolyFillRect.c, xorg/X11R7.6/rdp/rdpinput.c, xorg/X11R7.6/rdp/rdpmain.c, xorg/X11R7.6/rdp/rdpup.c, xrdp/lang.c, xrdp/xrdp.c, xrdp/xrdp_bitmap.c, xrdp/xrdp_mm.c, xrdp/xrdp_wm.c, xrdp/xrdpwin.c
I'm working on packaging xrdp for Amazon Linux. The hard stuff is still in the works. I'm pushing the trivial things first to get them out of the way.
=> Minor fixes

common/file.c
commented section are read as regular section. for instance:
#[section_name]
is read as :
[section_name]
this patch fix this issu and also :
- add few comments
- improve readability
Best regards
=> fix wrong handle of commented section in configuration file.

common/thread_calls.c, sesman/libscp/libscp_lock.c
Standard unnamed semaphores (sem_init, sem_destroy) are not functional on Mac OS. The compiler reports that they are deprecated.
So I used the Grand Central Dispatch implementation. It is standard on Mac OS, nothing needed to be installed (I have XCode installed already to have a development environment).
I considered using named semaphores (sem_open), but they can outlive the process and need special care to be cleaned up.
I made libscp_lock.c use semaphores through the thread_calls wrapper. That should work on all operating systems.
=> Add unnamed semaphore support on Mac OS

common/list.c, common/os_calls.h, keygen/keygen.c, libxrdp/xrdp_rdp.c, libxrdp/xrdp_sec.c, rdp/rdp_orders.c, rdp/rdp_rdp.c, sesman/chansrv/chansrv.c, sesman/chansrv/chansrv_fuse.c, sesman/chansrv/clipboard.c, sesman/chansrv/clipboard_file.c, sesman/chansrv/drdynvc.c, sesman/chansrv/rail.c, sesman/chansrv/smartcard.c, sesman/chansrv/smartcard_pcsc.c, sesman/chansrv/sound.c, sesman/chansrv/xcommon.c, sesman/session.c, tests/tcp_proxy/main.c, xrdp/xrdpwin.c, xup/xup.c
Fixing warnings to keep their number manageable. This also establishes a higher standard for the new code.
=> Warning fixes

docs/man/xrdp.ini.5
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
seriously obfuscated.
=> Mention the channel code in man page.

common/ssl_calls.c
Conditional preprocessor directives spread throughout the code set a bad
example.
The new backport code is located in one place. The compiler checks
argument types. The backport code has no access to the caller variables.
The main code has all advantages of the new, more compact API.
=> Use static inline functions for OpenSSL 1.0 backport

.travis.yml
Let's introduce continuous integration in order to automatically test build of pull requests.
=> CI: add .travis.yml

sesman/chansrv/chansrv.c, sesman/chansrv/pcsc/wrapper/winscard-funcs.h, xrdp/xrdp_types.h
A recent patch broke C++ compilation and added a few tabs. Let's fix that.
=> Code standards

common/os_calls.c
g_tcp_accept() and g_sck_accept() should use sockadd_in6 when IPv6 is
enabled. The former code logs client IP address always "0.0.0.0" in such
case.
Fixes #412.
=> common: Fix client IP address logging when IPv6 is enabled

sesman/chansrv/chansrv_fuse.c
All code changes are in the logs. That fixes the bulk of the warnings in the FUSE code.
=> Fix format warnings if FUSE is enabled

common/os_calls.c, common/os_calls.h, sesman/libscp/libscp_session.c, sesman/libscp/libscp_session.h, sesman/libscp/libscp_types.h, sesman/libscp/libscp_v0.c, sesman/libscp/libscp_v0.h, sesman/scp_v0.c, sesman/scp_v1.c, sesman/session.c, sesman/session.h, vnc/vnc.c, vnc/vnc.h, xrdp/xrdp_mm.c
This is cleanup of vncpassfile branch
=> vnc: change password file to use guid hash

.travis.yml
=> CI: correct pixman package name

libxrdp/xrdp_bitmap32_compress.c, libxrdp/xrdp_bitmap_compress.c, libxrdp/xrdp_orders.c
=> fixes for rle bitmap compress limits and raw bitmaps

sesman/env.c
It's a regression, the fix should be in 0.9.1. In previous versions, it was possible to have multiple VNC sessions. This should really fix #519
---
Every session uses its own VNC password, so keep then in separate files.
The old style password file uses the user's password encrypted with a
known key. Since we are not replacing it anymore, we should remove it.
=> Use per-display VNC password files, remove old style password if found

.travis.yml, common/xrdp_client_info.h, common/xrdp_constants.h, configure.ac, libxrdp/xrdp_caps.c, xrdp/Makefile.am, xrdp/xrdp_bitmap.c, xrdp/xrdp_painter.c, xrdp/xrdp_types.h, xrdp/xrdp_wm.c
=> add libpainter for drawing when client does not have minimum orders

.travis.yml, libxrdp/libxrdp.c, libxrdp/xrdp_caps.c
function not used for year,
part of noorders
=> fixes for bitmap update

.travis.yml
Use separate entries for every command. Travis CI would still run the
commands sequentially, and it would provide better annotation for the
output.
=> .travis.yml: use -Werror, test two configurations - minimal and maximal

xorg/X11R7.6/Mesa-7.10.3.patch, xorg/X11R7.6/buildx.sh, xorg/X11R7.6/libpciaccess-0.12.0.patch, xorg/X11R7.6/pixman-0.30.0.patch, xorg/X11R7.6/rdp/Makefile, xorg/X11R7.6/rdp/rdp.h, xorg/X11R7.6/x11_file_list.txt, xorg/X11R7.6/xorg-server-1.9.3.patch
The most important fix is restoring the download cache functionality that was broken by 6b589569ee2aeb20f157ef73b2ca240166fef6a4
=> Some good things extracted from the X11rdp MacOS port

libxrdp/libxrdp.c, libxrdp/libxrdp.h, libxrdp/libxrdpinc.h, libxrdp/xrdp_rdp.c, neutrinordp/xrdp-neutrinordp.c, neutrinordp/xrdp-neutrinordp.h, xrdp/xrdp.h, xrdp/xrdp_mm.c, xrdp/xrdp_types.h
Support Save Session Info PDU in proxy scenario
https://msdn.microsoft.com/en-us/library/cc240636.aspx
That one should solve #623
=> Pass session info in proxy mode

sesman/session.c
it is not only unnecessary but causes another bug.
=> sesman: remove unnecessary fork for FreeBSD

instfiles/xrdp-sesman.service, instfiles/xrdp.service
* Add Documentation field so the systemctl help command works.
* Remove syslog.target as syslog is normally socket-activated now.
=> Some fixes/improvements to service files.

docs/man/sesman.ini.5.in, sesman/sesman.ini
it gives users false hope and finally disappoints them.
=> docs: remove IdleTimeLimit until it is actually implemented

m4/ax_type_socklen_t.m4
Please see https://github.com/peti/autoconf-archive/pull/103 for the original PR
=> Update m4/ax_type_socklen_t.m4, it works with -Wall now

sesman/chansrv/pulse/module-xrdp-sink.c
It was undiscovered due to pulse module is currently not tested by travis.
=> chansrv: fix warnings in pulse module

astyle_config.as
=> Remove --break-blocks option, it doesn't match the existing code style

.travis.yml
=> Add i686 check in Travis CI

libxrdp/xrdp_rdp.c
Now client addr and port are properly logged.
=> Remove useless comment, no logic change

Makefile.am, readme.txt
It's better to have fewer files containing the source version.
=> Remove readme.txt, it has been replaced by README.md

common/Makefile.am, common/xrdp_sockets.h, libxrdp/libxrdp.h, sesman/chansrv/chansrv.c, sesman/chansrv/pulse/module-xrdp-sink.c, sesman/chansrv/pulse/module-xrdp-source.c, sesman/chansrv/sound.c, sesman/sesman.h, sesman/session.c, sesman/tools/dis.c, xrdp/xrdp.h, xrdp/xrdp_mm.c, xrdpapi/xrdpapi.c
Include xrdp_sockets.h directly, not through headers.
=> Rename file_loc.h to xrdp_sockets.h, install it

.gitignore, common/xrdp_sockets.h, sesman/chansrv/pulse/Makefile, sesman/chansrv/pulse/module-xrdp-sink.c, sesman/chansrv/pulse/module-xrdp-source.c, sesman/env.c
#743 for v0.9 branch
**Please don't merge this until #743 merged!**
=> make audio sockets path configurable (v0.9)

common/ssl_calls.c
Backport of #459. This should close #739.
=> Fix ssl_calls for OpenSSL 1.1.0

xrdp/xrdp_wm.c
As some clinents (AFAIK Windows 10) always send domain name, the backend
module is not selected properly. This causes the default usage with
Windows 10 fails with 'xrdp_wm_log_msg: Section "XXX" not configured'.
=> Pick up the first section if given section(domain) doesn't match anything

xrdp/xrdp_keyboard.ini
=> sort xrdp_keyboard.ini

xrdp/xrdp_keyboard.ini
Inspired by: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/xrdp-devel/Yerqa1umvJk/hwy6l7eKAgAJ
=> add Spanish keylayout

.travis.yml
it is the latest stable branch.
=> travis: enable build test on v0.9 branch

common/os_calls.c, sesman/sesman.c
This PR should replace #802 and solves #801.
=> Ensure socket directory present

NEWS.md
Update NEWS and mention about Win 10 RFX issue.
=> Prepare v0.9.3

common/os_calls.c
This is a final change before v0.9.3.
=> common: fix more glitches in  IPv4 initialization

configure.ac, instfiles/pam.d/Makefile.am, instfiles/pam.d/mkpamrules, instfiles/pam.d/xrdp-sesman.freebsd
as existing xrdp-sesman.unix doesn't suit FreeBSD.
=> Add a pam file for FreeBSD

common/xrdp_constants.h, sesman/chansrv/sound.c
I'm planning to introduce additional audio codecs such as ADPCM or AAC.
Let me refactor a little bit. Supporting more codecs make if-else-if-else deeper. Using switch-case instead.
=> Small refactoring before adding new audio codec

NEWS.md, README.md, configure.ac, instfiles/Makefile.am
#848 is an issue of release tarball. The new release should be made.
=> Release v0.9.3.1

common/os_calls.c
The string created by the function is especially used to pass client's IP address from xrdp to xrdp-sesman.
There's lots of things to make IP address logging better but just fix `g_write_ip_address()` always returns `0.0.0.0` at this time.
Logged in xrdp-sesman.log.
Before:
```
[20170828-13:55:22] [INFO ] ++ created session (access granted): username centos, ip 0.0.0.0:63080 - socket: 12
```
After:
```
[20170919-07:34:09] [INFO ] ++ created session (access granted): username centos, ip ::ffff:192.168.0.30:64578 - socket: 12
```
=> common: fix g_write_ip_address() didn't return correct IP address

.travis.yml
Before testing --enable-vsock, let's test these two.
=> travis: add build test on FDK AAC, Opus

sesman/chansrv/chansrv.c
=> chansrv: add LOG_LEVEL_TRACE here, too

common/os_calls.c
Looks like I forgot to add this in the original commit. This now will avoid logging messages about unknown connections on unknown families and give better output.
Ex: "AF_VSOCK connection received from cid: -1 port: 3389"
> -1 for clarity:
> ```C
> #define VMADDR_CID_ANY -1U
> ```
=> Implements the accept/close logic for vsock

common/log.c, xrdp/xrdp_listen.c
See each commit message for the reasons why I removed these logs.
=> Suppress some logs

sesman/sesman.ini, xrdp/xrdp.ini
=> sesman: comment on non-suid Xorg in sesman.ini

README.md, configure.ac, xorg/X11R7.6/rdp/rdp.h
=> Bump version to v0.9.5

sesman/chansrv/devredir.c
=> devredir: fix xinode leak

sesman/libscp/libscp_v1c.c, sesman/libscp/libscp_v1c_mng.c
=> fix leak of SCP_DISCONNECTED_SESSION

sesman/startwm.sh
as it sources bash_profile. And add comments.
Closes #1009.
=> sesman: default startwm.sh should use bash

sesman/env.c
VNC password file will be like: `~/.vnc/sesman_passwd-meta@example.xrdp.org:10`.
=> sesman: rename vnc password file, just a cosmetic change

NEWS.md, README.md, configure.ac, xorg/X11R7.6/rdp/rdp.h
=> Prepare release for v0.9.6

configure.ac
echo a summary of configure setting at the end on configure
=> echo configure summary

docs/man/sesman.ini.5.in, sesman/sesman.ini.in
I'm working on implementing disconnection by idle timeout. Will be included in xorgxrdp v0.2.9.
=> Ressurect IdleTimeLimit

common/xrdp_client_info.h, libxrdp/xrdp_caps.c, libxrdp/xrdp_orders.c, libxrdp/xrdp_rdp.c, xrdp/xrdp.ini.in
No Fonts desplayed on iOS with the Microsoft Remote Desktop 10.2.2(1291), issue #367
=> Support Cache Glyph Revison 2, issue #367

sesman/chansrv/sound.c
Original fix provided by takefu. See also:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233556
=> Fix build with FDK AAC v2

docs/man/xrdp-sesman.8.in, docs/man/xrdp-sesrun.8.in, xrdp/xrdpwin.c
* Put xrdp- prefix to some executables etc
* Eliminate sourceforge links
=> docs: Put xrdp- prefix to some executables etc

common/xrdp_client_info.h, libxrdp/xrdp_caps.c, libxrdp/xrdp_rdp.c, neutrinordp/xrdp-neutrinordp.c, neutrinordp/xrdp-neutrinordp.h, vnc/vnc.c, vnc/vnc.h, xrdp/xrdp.h, xrdp/xrdp_mm.c, xrdp/xrdp_types.h, xrdp/xrdp_wm.c, xup/xup.c, xup/xup.h
Pass suppress event to xrdp modules.  Allows xrdp backends to handle the suppress
=> handle TS_SUPPRESS_OUTPUT_PDU

common/os_calls.c, common/os_calls.h, common/trans.c, common/trans.h, xrdp/xrdp.c, xrdp/xrdp.h, xrdp/xrdp.ini.in, xrdp/xrdp_listen.c, xrdp/xrdp_types.h
Allow xrdp to listen on more than one port.  Controlled by xrdp.ini.  Support old file format and -p command line option.
=> Listen list

sesman/chansrv/pcsc/xrdp_pcsc.c
This PR addresses the warnings generated by cppcheck for `xrdp_pcsc.c` mentioned in #1473
The first of these relates to this code following line 1067:-
```
// TODO figure out why recv pci does not work
if (1 || (pioRecvPci == 0) || (pioRecvPci->cbPciLength < 8))
{
got_recv_pci = 0;
.  . .
}
else
{
got_recv_pci = 1;
.  .  .
/* pioRecvPci dereferenced */
}
. . .
if (got_recv_pci == 0)
{
. . .
}
else
{
/* pioRecvPci dereferenced again */
}
```
The `1 ||` in the if statement was added in commit 9f8d3697472ce8dc6353172e9a471568d1aec45e for XRDP 0.8.0 and has the effect of disabling the recv pci functionality. As a result, pioRecvPci is never dereferenced. However cppcheck is not clever enough to pick up that `got_recv_pci` is being used as a discriminant for the second block, and so generates …
=> xrdp_pcsc: Fix cppcheck 1.82 + 1.90 warnings

xrdp/xrdp_wm.c
Fix #397
Workaround by ignore odd shift message
=> workaround odd shift behaviour

docs/man/sesman.ini.5.in, docs/man/xrdp-dis.1.in
Minor fixes to man pages
Also addresses #1607
=> Minor manpage fixes

sesman/sesman.ini.in
=> sesman.ini: Update Xorg path for CentOS 8

faq-compile.txt
This documentation is to help new contributors to the project configure continuous integration to test a change before making a pull request.
=> Adding an FAQ entry for configuring Travis CI and Cirrus CI for a fork

neutrinordp/xrdp-neutrinordp.c
=> Fix compilation warnings/errors in xrdp-neutrinordp.c

.travis.yml, configure.ac, sesman/chansrv/chansrv_fuse.c
This pull request resolves #1678 by adding explicit int to pointer casts to resolve the compiler warnings/errors.
=> Fix warnings in chansrv_fuse.c

sesman/chansrv/chansrv_fuse.c
Follow up from the discussion in #1678 about the multiple types assigned to the fuse file handle callback context.
fuse_file_info.fh field is used to store a pointer two different types: an xfuse_handle and a xfs_dir_handle. There is no type identifier in the handle, so without further investigation it is not clear if there type error in the code.
use a single type in `fuse_file_info.fh` by adding a `xfs_dir_handle` pointer as a field of `xfuse_handle` and then only set the `xfuse_handle` pointer as the `fuse_file_info.fh` field.
* No testing performed.
* I haven't setup xrdp with a client that uses the fuse file system for manual testing, nor do I know which rdp functionality to execute to exercise this code.
* No unit test coverage of this functionality 
* I'm not an expert on the fuse …
=> Use a single type for the fuse file handle callback context

sesman/session.c
Problem with start bash script with parameters on xrdp as follows - **rdesktop -s "/my/bash/script.sh parameters" ip_address** . If you try this - xrdp run startwm.sh instead you script.
This patch fixed this issue.
=> Solve problem with run bash script with parameters on xrdp. 

common/log.c, common/log.h, docs/man/xrdp-sesrun.8.in, sesman/config.c, sesman/tools/sesadmin.c, sesman/tools/sesrun.c, xrdp/xrdp_mm.c
Following a [gitter chat](https://gitter.im/neutrinolabs/xrdp-questions?at=5fc78aa047d76318fd2628f2), some fixes to the sesrun doc and code improvements.
I've gotta dash now, so there's a chance the CI will fail. In the meantime comments welcome.
=> sesrun improvements and doc fixes

configure.ac, sesman/chansrv/chansrv.c, sesman/session.c
Mainly cosmetic fixes for minor issues raised recently - see #1715 and #1749
=> Cosmetic fixes for minor issues

common/arch.h, sesman/chansrv/sound.c
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> riscv doesn't require pointers to be aligned

README.md
and replace "Environment" section.
=> README: mention platform support tier

.cirrus.yml, .gitignore, common/Makefile.am, common/os_calls.c, common/os_calls.h, common/string_calls.c, common/string_calls.h, configure.ac, scripts/install_xrdp_build_dependencies_with_apt.sh, sesman/session.c, tests/Makefile.am, tests/common/Makefile.am, tests/common/test_common.h, tests/common/test_common_main.c, tests/common/test_string_calls.c, tests/memtest/Makefile.am
Adding logs to sesman/session.c to help a sys admin understand why a session failed to start.
=> Adding logs to sesman/session.c

libxrdp/xrdp_rdp.c, xrdp/xrdp_wm.c
=> Demote some too verbose logs to TRACE level
