neutrinolabs/xrdp

- common/os_calls.c
- configure.ac
See also neutrinolabs/xrdp#30.
Just removed redundunt non-ipv6 codes in g_tcp_connect but I'm not sure around line 715.
Thanks in advance.
```
#if !defined(NO_ARPA_INET_H_IP6)
#else
p.ai_flags = AI_ADDRCONFIG;
p.ai_family = AF_INET;
res = getaddrinfo(address, port, &p, &h);
#endif
```
> add experimental ipv6 option

- sesman/sesman.c
original code successfully builds with gcc but fails with clang.
> sesman: void function should not return a value

- xrdp/xrdp.c
- log_start should be after help and version
- Fixes neutrinolabs/xrdp#33.
Test result
-----------------
Build and ensure xrdp.ini does not exist.
```
$ ./bootstrap && ./configure && make
$ ls /etc/xrdp/xrdp.ini
ls: cannot access /etc/xrdp/xrdp.ini: No such file or directory
```
Executing xrdp fails as xrdp.ini does not exist.
```
$ xrdp/xrdp
We could not open the configuration file to read log parameters
Error reading configuration for log based on config: /etc/xrdp/xrdp.ini
log_start error
```
`-h` and `-v` should always succeed even if xrdp.ini does not exist.
```
$ xrdp/xrdp -h
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Usage: xrdp [options]
--help: show help
--nodaemon: don't fork into background
--kill: shut …
```
> xrdp: fix -h -v option if xrdp.ini is invalid

- sesman/chansrv/chansrv_fuse.c
chansrv_fuse.c includes chansrv_fuse.h even if XRDP_FUSE is not
defined. However, time_t is used in chansrv_fuse.h.  This causes
build failure on FreeBSD.
```
gmake[1]: Entering directory '/home/meta/github/metalefty/xrdp/sesman/chansrv'
gcc -DHAVE_CONFIG_H -I. -I../.. -I../../common    -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/local/sbin\" -DXRDP_SHARE_PATH=\"/usr/local/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\"   -I/usr/local/include -MT chansrv_fuse.o -MD -MP -MF .deps/chansrv_fuse.Tpo -c -o chansrv_fuse.o chansrv_fuse.c
In file included from chansrv_fuse.c:61:
chansrv_fuse.h:34: error: expected specifier-qualifier-list before 'time_t'
Makefile:473: recipe for target 'chansrv_fuse.o' failed
gmake[1]: *** [chansrv_fuse.o] Error 1
gmake[1]: Leaving directory …
```
> chansrv: explicit include in chansrv_fuse.c

- configure.ac
fuse has fuse.pc file for pkg-config. this is more reliable.
Tested on CentOS 7.
If fuse-devel is not installed, configure fails.
```
$ ./bootstrap && ./configure --enable-fuse
(snip)
checking security/pam_appl.h presence... yes
checking for security/pam_appl.h... yes
checking for struct in6_addr.s6_addr... yes
checking for FUSE... no
configure: error: please install libfuse-dev or fuse-devel
```
If fuse-devel is installed.
```
$ sudo yum -y install fuse-devel
$ ./bootstrap && ./configure --enable-fuse
(snip)
checking security/pam_appl.h usability... yes
checking security/pam_appl.h presence... yes
checking for security/pam_appl.h... yes
checking for struct in6_addr.s6_addr... yes
checking for FUSE... yes
(snip)
$ make clean
$ make >/dev/null 2>&1 && echo 'build success!!'
build success!! …
```
> configure: use PKG_CHECK_MODULES to check fuse

- sesman/chansrv/chansrv_fuse.c
FreeBSD/OpenBSD/NetBSD and OS X don't have errno EREMOTEIO.
> fuse: use EIO instead of EREMOTEIO for BSDs

- configure.ac
- xrdp/xrdp_mm.c
OpenPAM is used in FreeBSD, NetBSD, DragonFly BSD and Mac OS X.
On the Linux system, Linux-PAM is used.  Detect PAM during configure
and use which the system has.
Test result
=======
FreeBSD system
-----------------
Successfully builds, authentication fails with wrong username & password, authentication succeeds with correct username & password.
```
FreeBSD $ ./bootstrap && CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./configure --prefix=/tmp/xrdp-openpam
FreeBSD $ gmake && gmake install
FreeBSD $ /tmp/xrdp-openpam/sbin/xrdp-sesman --nodaemon
FreeBSD $ sesman/tools/xrdp-sestest
[20150314-15:14:43] [WARN ] [init:46] libscp initialized
001 - send connect request
ERR: resend credentials - Wrong username and/or password
username:meta
password:foobar
ERR: resend credentials - …
```
> xrdp: xrdp_mm.c detect and use OpenPAM

- instfiles/Makefile.am
- instfiles/init.d/Makefile.am
On systemd system, at least CentOS 7, `service foo start` command
works as wrapper of `systemctl start foo`.  However, xrdp installs
init script into /etc/init.d/xrdp.  This script is not necessary
for systemd system, and, what is worse,  if init.d/xrdp exists,
`service xrdp start` works as wrapper to run init.d/xrdp. Maybe
this is inconvinient for many users.
> instfiles: init.d/xrdp shouldn't be installed on systemd system

- common/ssl_calls.c
According to document[1][2][3], retry when SSL_get_error returns
SSL_ERROR_WANT_READ/SSL_ERROR_WANT_WRITE.
[1] https://www.openssl.org/docs/ssl/SSL_read.html
[2] https://www.openssl.org/docs/ssl/SSL_write.html
[3] https://www.openssl.org/docs/ssl/SSL_accept.html
> common: fix #248 TLS on FreeBSD

- sesman/session.c
sesman: merge FreeBSD local patch for session.c
net/xrdp: effective login name is not set by xrdp-sesman
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=157282
Long ago, I got some ideas  from OpenSSH's session.c licensed under "2-clause BSD license".
There's no problem re-licensing BSD licensed OpenSSH origin code by "Apache License 2.0". 
However,  showing original author(s) is necessary.
> sesman: merge FreeBSD local patch for session.c

- docs/man/xrdp-keygen.8
the manpage was taken from Debian, so it’s written by Vincent Bernat and GPL licenced; please merge this
> merge copyright and licence for this file from where it was taken from

- sesman/session.c
The session match logic had two versions - one for the
SESMAN_SESSION_TYPE_XRDP and SESMAN_SESSION_TYPE_XORG sessions and one
for every other type. The only difference was, that different display
sizes where ignored when searching for sessions to reconnect if the
policy does not have the SESMAN_CFG_SESS_POLICY_D flag set and the type
is SESMAN_SESSION_TYPE_XRDP or SESMAN_SESSION_TYPE_XORG.
The reason was that xvnc cannot resize and the others can do. This two
versions where not necessary because we set the
SESMAN_CFG_SESS_POLICY_D flag every time we have a xvnc session a few
lines above. So the two branches for the different types can be reduced
to one.
Signed-off-by: Jan Losinski <losinski@wh2.tu-dresden.de>
> Simplify session match logic.

- xorg/X11R7.6/x11_file_list.txt
as it rarely fails to build. Nobody actually needs fontconfig docs
to build and run x11rdp even if it builds successfully. Thus we can
just disable it.
Reported in scarygliders/X11RDP-o-Matic#53.
> X11rdp: disable fontconfig docs

- sesman/env.c
Setting LANG to en_US.UTF-8 suppresses language settings from
/etc/locale.conf
See https://bugzilla.redhat.com/show_bug.cgi?id=1290820
> sesman: don't set LANG, let initialization scripts take care of it

- common/os_calls.c
- configure.ac
Checking `struct in6_addr.s6_addr` is only valid for GNU/Linux. This is the reason why IPv6 not working on FreeBSD.  Another fix is still needed for OpenBSD.  I'm still working on OpenBSD issue at #30.
And one more thing, add `--enable-ipv6only` option for debug. This can be `--disable-ipv4`. Which do you like? I think `--disable-ipv4` is better if IPv6 is enabled by default but it is disabled now.
> Unbreak IPv6 on FreeBSD and add IPv6-only option

- configure.ac
The fix for AC_CONFIG_MACRO_DIRS is important, even though it only affects those who compile from the git repository.
AC_CONFIG_MACRO_DIR is much more portable than AC_CONFIG_MACRO_DIRS. AC_CONFIG_MACRO_DIR comes from from Autoconf, AC_CONFIG_MACRO_DIRS comes from Automake (as strange as it sounds) and requires a very recent version of Automake. Developers on RHEL and other conservative systems will be inconvenienced if it's not fixed.
> Hot fix for recent autotools changes

- sesman/libscp/libscp_session.c
- sesman/libscp/libscp_v0.c
- sesman/libscp/libscp_v1s.c
- vnc/vnc.c
The support is not ideal, acceptable. For some clients, 32 bpp is the only option.
scp_session_set_bpp() was essentially setting bpp to 0 if 32 bpp was requested. Check the error now, log errors, don't continue with "0 bpp".
Allow 32 bpp in scp_session_set_bpp() - that's the global switch.
Allow 32 bpp in VNC, use switch statement for readability.
> Make it possible to use Xvnc with 32 bpp

- Makefile.am
- common/Makefile.am
- libxrdp/Makefile.am
- mc/Makefile.am
- neutrinordp/Makefile.am
- rdp/Makefile.am
- sesman/Makefile.am
- sesman/chansrv/Makefile.am
- sesman/libscp/Makefile.am
- sesman/tools/Makefile.am
- vnc/Makefile.am
- xrdp/Makefile.am
- xrdpapi/Makefile.am
- xrdpvr/Makefile.am
- xup/Makefile.am
It's better to have headers in the same lists as the *.c files. Automake distributes sources by default and doesn't generate any compile rules for header files listed as sources, so there should be no functional difference.
While testing with older versions of Automake, I found that m4 is not distributed, so I added it to EXTRA_DIST.
> More makefile cleanup

- sesman/chansrv/pulse/module-xrdp-sink.c
- sesman/chansrv/pulse/module-xrdp-source.c
Discovered in #321.  The number of argument for pa_rtpoll_run have
been changed since 6.0.
\>=6.0 : int pa_rtpoll_run(pa_rtpoll *f);
<6.0  : int pa_rtpoll_run(pa_rtpoll *f, bool wait);
Check pulseaudio version by PA_CHECK_VERSION macro introduced since
pulseaudio 0.9.16.  In case PA_CHECK_VERSION is not defined,
pa_rtpoll_run takes 2 arguments.
> pulse: fix build pulseaudio 6.0 or higher

- docs/man/Makefile.am
- instfiles/Makefile.am
- instfiles/default/Makefile.am
- instfiles/init.d/Makefile.am
- instfiles/init.d/xrdp
- instfiles/pulse/Makefile.am
- instfiles/rc.d/Makefile.am
- instfiles/rc.d/xrdp
- keygen/Makefile.am
- sesman/Makefile.am
- xrdp/Makefile.am
The big thing - installing rsakeys.ini by "make install". Not need to remember to do that for manual install. No need to rely on the init scripts.
More Automake cleanups. Using standard Automake features for installing scripts and making data files distributable.
> Key install

- common/os_calls.h
- configure.ac
- m4/.gitignore
- m4/ax_append_flag.m4
- m4/ax_cflags_warn_all.m4
- m4/ax_gcc_func_attribute.m4
- m4/ax_require_defined.m4
- xrdp/xrdp.c
- xrdp/xrdpwin.c
Group all initial sanity checks together. Check for rsakeys.ini in that function. Show full name of the PID file in error messages.
Enable -Wall and warnings for printf arguments. Use Autoconf Archive macros to check for those features, as they are not universal, but not limited to gcc.
> Sanity checks

- sesman/config.h
- sesman/sesman.ini
- sesman/session.c
In RHEL and its clones, /usr/bin/Xorg is set suid-root. To execute
Xorg with user privileges, /etc/pam.d/xserver needs be edited [1],
or suid bit of Xorg binary needs to be dropped.
In order to keep Xorg and /etc/pam.d/xserver untouched, preparing
non-suid version of Xorg as /usr/bin/Xorg.non-suid for example is
the simplest solution. However, Xorg.non-suid cannot be executed
since it is hardcoded to execute Xorg in sesman.
This change makes more flexible to execute Xorg with non-standard
name or not in PATH environment variable.
[1] https://www.centos.org/forums/viewtopic.php?t=21185
> sesman: do not hardcode Xorg/X11rdp/Xvnc executables

- common/os_calls.c
in case getaddrinfo(3) might fail.
In FreeBSD, AI_V4MAPPED support for getaddrinfo(3) was very recently
implemented[1].  Most of FreeBSD systems in the world do not have
this implementation yet.  This will be a problem when AI_V4MAPPED
isn't supported and xrdp is built with IPv6 option.  In such a case,
g_tcp_connect always fails.
Of course getaddrinfo(3) might fail in other cases.  The log helps
us to know what's happening.
[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198092
> common: add log for g_tcp_connect

- sesman/chansrv/clipboard.c
- sesman/chansrv/devredir.c
- xrdpapi/xrdpapi.c
- xup/xup.c
This should make xrdp warning-free and set a higher standard for new code contributions.
> Fix warnings reported by gcc 5.3.0 on Mac OS

- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/clipboard_file.c
When xfuse_create_file_in_xrdp_fs is failed, it returns NULL.
Without this fix, xinode->size causes SEGV, so implementation is changed
to return -1 and check the return value in caller.
> chansrv: avoid chansrv SEGV when xinode is NULL

- xorg/X11R7.6/xkeyboard-config-2.0.patch
- xrdp/xrdp_keyboard.ini
PC105-jp keyboard need xkeyboard-config version 2.11 or later. 
xkeyboard-config version 2.11 or later need libX11 version 1.4.3 or later. 
I was build XRDP with xkeyboard-config-2.11 and libX11-1.4.3.
But it was not accept keyboard.
I was done backport because there is no way.
This is the interim fix.
Please build someone X11 by the newer libraries.
> Fix pc105-jp-Henkan key.

- sesman/env.c
to enable to execute FUSE mount program.
The place of FUSE mount programs are:
FreeBSD   : /sbin/mount_fusefs
GNU/Linux : /bin/fusermount
See also #387.
> sesman: Add /sbin to PATH for FreeBSD

- libxrdp/xrdp_rdp.c
Improve some certificate related logged messages
from
```
[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
```
to
```
[INFO ] Missing definition of x.509 certificate, use default instead: /etc/xrdp/cert.pem
[INFO ] Missing definition of x.509 key file, use default instead: /etc/xrdp/key.pem
```
resp.
```
[WARNING] No absolute path to X.509 certificate, use default instead: /etc/xrdp/cert.pem
[WARNING] No absolute path to x.509 key file, use default instead: /etc/xrdp/key.pem
```
> Improve certificate log messages

- xorg/X11R7.6/x11_file_list.txt
Python 2.7 cannot build with OpenSSL 1.0.2h pointed out in #399.
Python-2.7.11.tar.xz needs to be uploaded to server1.xrdp.org.
I've confirmed X11rdp successfully builds with python 2.7.11 and built X11rdp properly works.
Please don't forget to upload tarball to server1.xrdp.org before merge this.
> X11rdp: update python 2.7 -> 2.7.11

- common/os_calls.c
broken by #314. This is compatible with the fix introduced in #314.
To use non-ASCII text/filename in clipboard, chansrv needs to be run
with LC_CTYPE=\*.UTF-8 because the behaviour of mbstowcs(3) function
called in chansrv depends on LC_CTYPE[1].  However #314 made
LC_CTYPE=C in chansrv context.  Even if LANG and LC_\* are set in
.bashrc, /etc/profile, /etc/locale.conf or something like that,
it doesn't affect in chansrv context because chansrv doesn't source
any of them unlike sesman.
So do not set LC_CTYPE to blank or "C" in g_init() in order to get
g_mbstowcs and g_wcstombs to work properly with non-ASCII UTF-8
characters in any context.
Setting LC_CTYPE to *.UTF-8 doesn't obstruct applying system
language in RHEL [2].
[1] Linux man page says:
The behavior of mbstowcs() depends on the …
> Fix clipboard when text/filename contains non-ASCII characters

- libxrdp/xrdp_sec.c
Example of xrdp_keyboard.ini for russian keyboard (Please add this to wiki) 
[default_rdp_layouts]
rdp_layout_us=0x00000409
rdp_layout_de=0x00000407
rdp_layout_fr=0x0000040C
rdp_layout_it=0x00000410
rdp_layout_jp=0x00000411
rdp_layout_jp2=0xe0010411
rdp_layout_jp3=0xe0200411
rdp_layout_jp4=0xe0210411
rdp_layout_ru=0x00000419
rdp_layout_se=0x0000041D
rdp_layout_pt=0x00000816
rdp_layout_br=0x00000416
rdp_layout_pl=0x00000415
[rdp_keyboard_ru]
keyboard_type=4
keyboard_subtype=1
model=pc105
options=grp:alt_shift_toggle
rdp_layouts=default_rdp_layouts
layouts_map=layouts_map_ru
[layouts_map_ru]
rdp_layout_us=us,ru
rdp_layout_ru=us,ru
> Allows use the xkb options that for example allows you to specify a key combination to change the layouts.

- sesman/chansrv/clipboard_file.c
Hi, I fixed one more clipboard bug.
Can't copy&paste file when the file is located in a directory its name contains non-ASCII or ASCII non-alphanumeric chars.
For example:
* /home/centos/directory name contains whitespace/somefile.bin
* /home/centos/ダウンロード/日本語のファイル.bin
Built by RH-Matic. Client is Windows 10's mstsc.exe.
~~~
$ rpm -qa |grep xrdp
xrdp-0.9.0.git5cd61ff+devel-1.el7.centos.x86_64
xorg-x11-drv-xrdp-0.9.0.gita0add6c+fix_utf8_clipboard-1.el7.centos.x86_64
~~~
Always.
Copy these two files to clipboard.
* $HOME/space directory/space filename.jpeg
* $HOME/space directory/space filename (コピー 1).jpeg
~~~
[3651253284]: CLIPFILE   clipboard_get_file: 215 : ERROR: clipboard_get_file: file [/home/centos/space%20directory/space filename.jpeg] does not exist
[3651253284]: CLIPFILE …
> Fix clipboard fle when directory name contains non-ASCII or ASCII non-alphanumeric chars

- libxrdp/xrdp_sec.c
- xorg/X11R7.6/rdp/rdpinput.c
Setting xkb options is added  in #364 but options are not applied to x11rdp.
This is already implemented for xorgxrdp.
And some more logs.
> Apply xkb options for x11rdp

- common/os_calls.c
- configure.ac
- m4/ax_type_socklen_t.m4
- sesman/scp.c
- sesman/session.c
- sesman/sig.c
- sesman/tools/sesrun.c
- tests/gtcp_proxy/gtcp.c
- tests/tcp_proxy/main.c
- xrdp/xrdp_listen.c
Make g_sck_close() do the right thing (check errors, make sure it's actually a closing socket, use proper debug levels) and add actually useful debug information (address family, local address and port).
Make fixes based on the information from g_sck_close()
Fix closing the listening socket twice in xrdp-sesman.
Use correct function to close g_term_event. It's not even a valid a file descriptor.
Cleanup useless references to g_sck in sesrun, also remove g_pid.
> Cleaning up bogus messages about closing "established" connections to NULL:NULL

- xorg/X11R7.6/x11_file_list.txt
> X11rdp: remove python as it isn't really needed these days

- .gitignore
- xorg/X11R7.6/.gitignore
- xorg/X11R7.6/buildx.sh
- xorg/X11R7.6/x11_file_list.txt
I'm trying to add DESTDIR support to buildx.sh, which would allow packaging it without sudo and other dirty magic. I'm not including that change, but I'm including smaller improvements that I made while working on a more ambitious goal.
buildx.sh had implicit dependencies on an existing X11 installation. By reordering the packages, those implicit dependencies are removed.
> Fixes for x11rdp build

- sesman/config.c
- sesman/config.h
- sesman/libscp/libscp_v1s.c
- sesman/scp.c
- sesman/scp_v0.c
- sesman/scp_v1.c
- sesman/scp_v1_mng.c
- sesman/session.c
- sesman/sig.c
Valgrind has found 4 memory leaks in xrdp-sesman. No leaks have been found in the xrdp binary. No memory leak is major, but it's good to fix them to keep our coding standards high.
> Fixing memory leaks

- xorg/X11R7.6/buildx.sh
Executing wget like
wget http://example.com/file1 http://example.com/file2 ...
can do HTTP keepalive.
Quit calling wget with single file. Downloading multiple files in one
http connection is a little bit faster than executing wget more than
100 times. And parallelly execute two instances of wget to increase
download speed.
> buildx.sh: download tarballs using keepalive

- xrdp/xrdp.ini
Make section names equal to the names in the "name=" setting to avoid
confusion and the need to renumber sections. Avoid "sesman-" in the
names, it's not helpful to the user. Move "Xorg" just below "X11rdp",
that would give xorgxrdp more visibility.
> Simplify names of xrdp.ini sections, rename "Session Manager" to "Xorg"

- docs/man/xrdp-chansrv.8
- sesman/chansrv/chansrv.c
like Xorg's logfile is written to ${XDG_DATA_HOME}/xorg/Xorg.n.log.
If XDG_DATA_HOME is not defined, the log path will be
${HOME}/.local/share/xrdp.
> chansrv: change chansrv log path to ${XDG_DATA_HOME}/xrdp

- common/Makefile.am
Installing the headers makes it possible to compile xorgxrdp as a
separate package, without xrdp sources.
> Install headers used by X11rdp and xorgxrdp

- xrdp/lang.c
upper 16 bits of keylayout value indicates keyboard layout.
lower 16 bits of keylayout value indicates country/language.
If the keymap file doesn't match exactly to keylayout value,
the typical keyboard of the country/language should be used.
For example [1]:
0x00000409: US English
0x00010409: US Dvorak
0x00020409: US International
0x00030409: US Dvorak for left hand
0x00040409: US Dvorak for right hang
0x0000040e: Hungarian
0x0001040e: Hungarian 101-key
[1] https://msdn.microsoft.com/windows/hardware/commercialize/manufacture/desktop/windows-language-pack-default-values
> Use km-0000yyyy.ini if km-xxxxyyyy.ini doen't exist

- common/os_calls.c
g_get_strerror() is simply returning strerror(errno) for now, except Windows. strerror() is not thread safe, we should replace it across the board. This PR simply restores consistency.
> Use g_get_strerror() instead of strerror(errno) for portability

- xorg/X11R7.6/buildx.sh
- xorg/X11R7.6/rdp/Makefile
Stripping X11rdp is unhelpful for anyone trying to debug it or run it in Valgrind. Let's keep the uninstalled binary unstripped.
Saying in a comment that X11RDPBASE needs to be set is not enough, let's check that it's set.
Linking static libraries two times is sloppy. It's not hard to reorder them properly.
> X11rdp build system fixes

- sesman/sesman.ini
Users assume that they need to renumber the parameters. That makes
parameter editing more involved than it needs to be.
> Omit numbers from the "param" keys, they are not needed

- xrdp/xrdp_wm.c
If no domain is passed, self->session->client_info->domain is an empty
string that is incorrectly treated as if the domain were passed by the
client.
The regression was introduced in fc753a95, when an incorrect check for
non-empty domain was added. That check was removed in 67119ecc based on
coverity report, leaving no trace of the original intention.
Check domain both for '_' and '\0' as the initial character. In either
case, select the first session type section in xrdp.ini.
> Fix regression in domain to session type mapping

- sesman/chansrv/chansrv_fuse.c
strncat() will copy at most the specified number of characters and append the null character on top of that. strlen() doesn't count the final null character.
This code will only be compiled if FUSE is enabled. I'm sure FUSE support needs a big cleanup. Even strcat() just about strncat() can have some issues.
However, I believe this misuse of strncat() should be fixed before the next release, because it sets a bad example and it's an antipattern detected by static code checkers.
> Fix potential buffer overflow in strncat() invocation

- sesman/verify_user.c
- sesman/verify_user_bsd.c
- sesman/verify_user_kerberos.c
- sesman/verify_user_pam_userpass.c
Include string.h for strcmp(). Don't define _XOPEN_SOURCE, it conflicts
with libc headers and hides putpwent(). Make input strings constant. Fix
functions to match their declarations.
> Fix compile warnings for non-default authentication methods

- keygen/Makefile.am
as many systems in the world still default to create SHA-1 certs if
hash algorithm is not specified explicitly.
> Do not create SHA-1 certificates anymore

- docs/man/sesman.ini.5
- docs/man/xrdp-chansrv.8
- docs/man/xrdp-dis.1
- docs/man/xrdp-genkeymap.8
- docs/man/xrdp-keygen.8
- docs/man/xrdp-sesman.8
- docs/man/xrdp-sesrun.8
- docs/man/xrdp-sessvc.8
- docs/man/xrdp-xcon.8
- docs/man/xrdp.8
- docs/man/xrdp.ini.5
- genkeymap/dump-keymaps.sh
- sesman/sesman.ini
- xrdp/xrdp.ini
- xrdp/xrdp_keyboard.ini
Lots of changes. Topics are:
- Add missing descriptions
- Update version
- Replace xrdp website links
- Use two different symbols to comment out *.ini files
- semicolon for descriptions in config files
- number sign for actual configurations
- Change order of parameters in xrdp.ini
- put same layer configuration parameters together
- TCP
- security layer
- RDP features (such as bpp, channels, compression, fast path, multimon)
- bring lower layer earlier
- Unify mixed boolean value expression to true/false
Documents are not still complete but big one step to keep up-to-date.
> Update man pages and config files

- keygen/Makefile.am
- keygen/openssl.conf
This also fixes "make distcheck", which expects "make uninstall" to
remove all installed files.
> Fix "unable to find 'distinguished_name' in config" with older openssl

- sesman/sesman.ini
Fedora patches sesman.ini to remove "-ac", and that doesn't cause any ill
effects.
> Remove "-ac" from X server parameters, it's insecure and unnecessary

- common/os_calls.c
The system to run xrdp does not necessarily support IPv6 even though
it is compiled with IPv6.
Fixes #432.
Issue #460 needs to be merged before merging this.
> common: If IPv6 not supported, fall back to IPv4

- libxrdp/xrdp_iso.c
- libxrdp/xrdp_rdp.c
Fixing some important issues with the security level negotiation.
`security_layer=negotiate` is not just documented, it's the default now. But the code fails to recognize that. Stop xrdp complaining about its default config file.
Log the security negotiation information - what was requested and what was decided. The only reason I settled for the DEBUG and not INFO level is because we don't have a function to print the flags in human readable format.
Don't select SSL if the SSL keys are missing and both the config file and the client allow RDP connections. Selecting SSL and failing is not a reasonable behavior.
> Security level fixes

- common/Makefile.am
- configure.ac
I checked OpenSSL as far back as 0.9.8e, and it has the openssl.pc file (generated by Makefile). The oldest supported version is 1.0.1u.
Some systems need `-ldl` to use `dlopen()`. libcommon calls `dlopen()`, it should not rely on other libraries linking `-ldl`.
> Find openssl by pkg-config, add -ldl if needed

- xorg/X11R7.6/rdp/rdprandr.c
gtk3 programs crash when they divide dotClock by hTotal and vTotal to
calculate the refresh rate.
> Provide reasonable hTotal, vTotal and dotClock for the display mode

- docs/man/xrdp.ini.5
- xrdp/xrdp.ini
xserverbpp affects X11rdp and Xvnc, but not Xorg. No need to have xserverbpp in the Xorg section where it has no effect. Add commented out xserverbpp to Xvnc, some users may want to experiment with that setting.
> Document xserverbpp, add it to Xvnc section, remove from Xorg section

- configure.ac
- sesman/session.c
The solution is not universal, but handy anyway, and it improves security. Using PR_SET_NO_NEW_PRIVS ensures that the setuid bit on Xorg would be ignored. Xorg can fail if run with root permissions, but the original user has no console access, as reported by PAM.
Tested on AWS t2.micro with Amazon Linux 2016.09.
> Disable privilege elevation by setuid for the X server

- sesman/sesman.ini
The log file is created in the home directory, %s is replaced with the
display number (e.g. 10).
If Xorg is run setuid root, it can refuse to run if the log path is
absolute.
> Change default Xorg logfile to .xorgxrdp.%s.log

- sesman/session.c
`username` here should be changed to `s->username`, too.
> sesman: unbreak FreeBSD build after #523

- common/os_calls.c
IPv6 addresses can have colons in their names, so the final colon can be confusing.
http uses [ip]:port, but this is just a log, we can be more user friendly.
> Don't use colon to separate IPv6 address from the port

- libxrdp/xrdp_caps.c
- xrdp/xrdp_encoder.c
o caps: advertise remotefx codec capsets only when supported (RFX mode, proxy mode)
o xrdp_encoder: do not initialze encoder context for RFX when rfxcodec is not supported
should resolve #534
> Fix for RemoteFX detection, avoid blank screen when RFX is not supported on server

- .gitmodules
This PR prepares the stage for the noorders branch. Moving back and forth through a commit that adds a submodule is quite painful, so let's get it merged so that further changes can be tested easily.
I used the latest commit of libpainter. It includes a fix for "make distcheck".
I also changes the git protocol used for librfxcodec from git to https. The git protocol is a bad choice in my opinion. See this writeup for example: https://gist.github.com/grawity/4392747
GitHub doesn't even advertise the git protocol. It recommends https. https://help.github.com/articles/which-remote-url-should-i-use/
This PR is for version 0.9.1, since we want noorders to be part of 0.9.1.
> Add libpainter submodule, update librfxcodec URL

- libxrdp/xrdp_jpeg_compress.c
Let's keep our standards high. We don't need any warnings. This is for 0.9.1, please.
---
If the image width is not divisible by 4, the image is padded to the next
multiple of 4. The additional pixels are filled with the colors of the
last pixel in the row.
The last pixel colors may not be initialized if the width is 0. In this
case, the would be no padding, but the compiler doesn't know that.
Add a check that the width is more that 0 before filling the padding.
> Fix a warning in jpeg compression code with --enable-jpeg

- Makefile.am
- configure.ac
- xrdp/Makefile.am
Since libpainter is going to become a subpackage, we can make librfxcodec
a subpackage as well.
With this change, librfxcodec is configured, built and linked to xrdp
automatically if enabled by "--enable-rfxcodec"
librfxcodec is packaged by "make dist" regardless of "--enable-rfxcodec"
librfxcodec/confgure is run unconditionally, it's needed for "make dist"
to work. But librfxcodec is only compiled if enabled.
> Make librfxcodec a subpackage

- Makefile.am
- configure.ac
This is a part of the noorders task for 0.9.1. With this change, libpainter will be configured and compiled automatically as part of the build.
> Make libpainter a subpackage of xrdp

- xrdp/xrdp_mm.c
Even seemingly harmless configuration changes can have unexpected consequences. This is a regression caused by my recent change in `xrdp.ini`, please fix it before 0.9.1.
---
The removal of "xserverbpp=24" from the Xorg entry lead to a regression.
Clients with a different bpp would not reconnect to an xorgxrdp session
if the client's bpp is different, even though xorgxrdp is always using 24
bpp.
Imply "xserverbpp=24" for "code=20" in xrdp.ini.
> Regression fix: session matching uses wrong bpp for Xorg

- docs/man/xrdp.ini.5
- xrdp/xrdp.ini
Setting autorun to empty keeps X11rdp as the default backend for
autologin (since it's the first section), but it also enables the backend
selection by the domain name.
Describe the autorun interaction with the domain name both in the config
file and in the manual.
> Set autorun to empty, improve autorun documentation

- Makefile.am
- genkeymap/Makefile.am
- instfiles/Makefile.am
- libxrdp/Makefile.am
- neutrinordp/Makefile.am
- sesman/Makefile.am
- sesman/chansrv/Makefile.am
- xrdp/Makefile.am
- xrdpapi/Makefile.am
- xrdpvr/Makefile.am
Another patch that needs to be in 0.9.1. I don't know in the 0.9.1 release will be made using `make dist`. If yes, it would be missing a lot of files that were included in older releases. Even the sources of X11rdp would not be included.
I believe that it would be better to err on the side of distributing files. If some files are truly useless, we should remove them from git first.
> Distribute all files except git and github specific data

- xrdp/xrdp_bitmap.c
This is for 0.9.1. This code was in the original noorders branch (d3d2bdc001f951d7b456256bca756d79a4556d6f) but wasn't submitted (yet).
---
self->line_size should be calculated in xrdp_bitmap_create_with_data()
The code was in the original noorders branch but got lost. Without this
fix, the image is garbled.
The client should be configured with compression disabled, or it will
disconnect. That's a known problem.
> Fix Parallels Client on Mac

- sesman/tools/sesadmin.c
This is for 0.9.1. The patch is minimal on purpose to minimize risks.
---
The help text mentions "LIST" and "KILL" commands, but the manual says
"list" and "kill", and the command line parser expects the later.
> xrdp-sesman: fix help text to match the manual and the actual behavior

- Makefile.am
- xrdp/Makefile.am
This is for 0.9.1 - fixes on top of the last noorders patches.
> Compile libpainter only if enabled, fix path to libpainter.a

- configure.ac
This is for 0.9.1. Users without nasm should still be able to compile xrdp if they don't specifically request rfxcodec.
> Don't fail without working nasm if rfxcodec is not enabled

- configure.ac
- docs/man/sesman.ini.5
- docs/man/xrdp-chansrv.8
- docs/man/xrdp-dis.1
- docs/man/xrdp-genkeymap.8
- docs/man/xrdp-keygen.8
- docs/man/xrdp-sesadmin.8
- docs/man/xrdp-sesman.8
- docs/man/xrdp-sesrun.8
- docs/man/xrdp-sessvc.8
- docs/man/xrdp-xcon.8
- docs/man/xrdp.8
- docs/man/xrdp.ini.5
- readme.txt
- xorg/X11R7.6/rdp/rdp.h
This is for 0.9.1, obviously, to be applied immediately before the release. We have many places where the version is used, let's take care of every occurrence. Please note that xrdp-sesadmin.8 uses 0.7.0 now, not 0.9.0.
> Update version to 0.9.1

- keygen/openssl.conf
Self-signed certificates lacks the required CA extensions.
MS RDP client for iOS cannot connect because of it. the app is crashing right after TLS handshake.
I think it worked before we added our openssl.conf file.
> keygen: add CA extensions to self-signed certificates

- configure.ac
No need to confuse the user by asking to install libX11 headers.
> When Xfixes.h is checked, the user should have libX11 already

- libxrdp/xrdp_caps.c
- xrdp/xrdp_mm.c
This should make RemoteFX usable with Parallels Client. they always want zero unacked frames on the wire.
> RFX: fix frame acks handling

- configure.ac
PKG_PROG_PKG_CONFIG does not exit if it fails to find pkg-config.
Continuing without pkg-config leads to misleading error messages when
checks for packages fail.
> Exit with error message if pkg-config is not found

- common/arch.h
- common/ssl_calls.c
- sesman/chansrv/chansrv.c
- sesman/chansrv/chansrv.h
- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/chansrv_fuse.h
- sesman/chansrv/devredir.h
- sesman/chansrv/irp.c
- sesman/chansrv/rail.c
- sesman/chansrv/sound.c
- sesman/libscp/libscp_init.c
- sesman/libscp/libscp_init.h
- sesman/libscp/libscp_session.c
- sesman/libscp/libscp_session.h
- sesman/session.c
- sesman/session.h
- sesman/tools/sesadmin.c
- xorg/tests/xdemo/xdemo.c
- xrdpapi/simple.c
In C, an empty argument list in a declaration means that the function
can accept any arguments. Use "void" instead, it means "no arguments".
C++ treats void and empty list as "no arguments".
> Use "void" for empty argument list in declarations

- libxrdp/xrdp_jpeg_compress.c
Actually use the error code from tjCompress() by logging the errors.
Make sure width is more than zero before filling the pad with the last
pixel data.
> Fix all warnings in TurboJPEG code

- sesman/chansrv/rail.c
It is already called above "if" with the same arguments.
> rail: remove unneeded call to XGetWindowAttributes()

- sesman/config.c
not max_idle_time. 
It looks like just a copy & paste mistake.
> sesman: print max_disc_time as DisconnectedTimeLimit

- common/trans.h
- sesman/chansrv/devredir.c
- sesman/chansrv/devredir.h
- sesman/libscp/libscp_v1c.c
- sesman/libscp/libscp_v1c_mng.h
This is a result of compiling xrdp with most warnings enabled and suppressing non-interesting warnings. This PR addressed duplicate and misplaced function declarations. It also fixes logging data that is not guaranteed to be initialized.
> Warning fixes

- common/xrdp_client_info.h
- libxrdp/libxrdp.c
- libxrdp/xrdp_rdp.c
- libxrdp/xrdp_sec.c
- xrdp/xrdp_mm.c
* Check for empty channel names, they are unusable. Jump Desktop client send empty channel names for disabled channels. That made xrdp think we got more channels then really negotiated via  Client MCS Channel Join Request PDUs. That fix makes Jump Desktop client work with xrdp (should resolve #594)
* Respect xrdp.ini channel blocking settings. The restriction was only applied on client to server channel data.  block PDUs coming from chansrv if channel is not allowed. This change can help with Parallels Client, which doesn't support our rdpsnd channel (#608). One can now block rdpsnd channel in xrdp.ini so Parallels Client will not drop the connection.
> Channels improvements

- configure.ac
- instfiles/pam.d/Makefile.am
- instfiles/pam.d/mkpamrules
- instfiles/pam.d/xrdp-sesman.debian
- instfiles/pam.d/xrdp-sesman.other
- instfiles/pam.d/xrdp-sesman.password-auth
- instfiles/pam.d/xrdp-sesman.redhat
- instfiles/pam.d/xrdp-sesman.suse
- instfiles/pam.d/xrdp-sesman.unix
Use easy to understand names for config files (debian, redhat, suse,
unix). Move all autodetection to a separate script.
> Allow PAM file selection in configure, improve autodetection, add SUSE

- common/ssl_calls.c
- common/ssl_calls.h
- common/trans.c
- common/trans.h
- libxrdp/xrdp_rdp.c
Hi, I've implemented logging of TLS version and cipher suggested at #422.
The purpose to log it is to know which client use which SSL/TLS version and cipher suites and confirm how safe it is.  For example, the feature to disable SSLv3 and choose cipher suite has been implemented. Disabling vulnerable SSL protocols or cipher suites affects some clients.   Logging help us to know which client is affected when vulnerable SSL protocols or cipher suites are disabled.
I know all SSL or encryption relevant codes are written in `common/ssl_calls.c` and `libxrdp/xrdp_sec.c` , however, in order to log client's IP address and TLS information together, there's only option for me to implement it in `libxrdp/xrdp_rdp.c`.  
This is really a draft.  If there's better way to log it, please leave comment …
> TLS: log TLS version and cipher

- xorg/X11R7.6/rdp/rdpup.c
The old code overwrites disconnect timeout to 60 sec when
XRDP_SESMAN_KILL_DISCONNECT is set to truthy value.
> x11rdp: respect disconnect timeout set by XRDP_SESMAN_MAX_DISC_TIME

- instfiles/xrdp-sesman.service
BindTo was left for compatibility.
https://lists.freedesktop.org/archives/systemd-commits/2012-July/002272.html
> Change BindTo to BindsTo, it was renamed in systemd long time ago

- xrdp/xrdp_painter.c
The second `x2` should be `y2`
> Fix incorrect argument to painter_line()

- sesman/chansrv/clipboard.c
[XChangeProperty](https://tronche.com/gui/x/xlib/window-information/XChangeProperty.html)'s last parameter is number of elements, not number of bytes.
Because of this bug, Paste did not work in any java applications.
Java checks all formats first and because bytes are always bigger than length, it reads further and once it finds a 0 value, check fails with java.lang.NullPointerException
As I checked other calls of XChangeProperty in clipboard.c are fine.
> Fix calling XChangeProperty in clipboard provide

- configure.ac
That's the text that pkg-config and configure output to stderr:
```
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
```
That's not useful on FreeBSD or Mac OS. It is still possible to specify
`--with-systemdsystemunitdir=DIR` manually on any OS.
> Only check for systemd on Linux, no need to warn users of other OSes

- configure.ac
- keygen/Makefile.am
Prefer openssl binary from the same location as the openssl library.
Make it possible to suppress certificate generation during install by
passing OPENSSL=: to make.
> Check for openssl binary in configure, don't fail if not found

- common/os_calls.c
- configure.ac
- sesman/session.c
This depends on https://github.com/neutrinolabs/xorgxrdp/pull/65 and https://github.com/neutrinolabs/librfxcodec/pull/14 however.
I’ve tested this with Debian (compile test only).
> Add GNU/kFreeBSD support

- sesman/tools/sesadmin.c
Example of improved output:
```
Session ID: 24952
Session type: 2
Screen size: 640x480, color depth 24
Idle time: 0 day(s) 0 hour(s) 0 minute(s)
Connected: 2017/01/26 00:11
Session ID: 23848
Session type: 3
Screen size: 1280x800, color depth 24
Idle time: 0 day(s) 0 hour(s) 0 minute(s)
Connected: 2017/01/26 00:07
Session ID: 13199
Session type: 1
Screen size: 1280x800, color depth 24
Idle time: 0 day(s) 0 hour(s) 0 minute(s)
Connected: 2017/01/25 23:02
```
> Several fixes for xrdp-sesadmin, including bad free() on error

- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_mm.c
ACCESS is defined unconditionally in the files that use it. No comments
exist about that macro. The code guarded by the macro is PAM related.
> Don't use ACCESS macro

- common/ssl_calls.c
- common/ssl_calls.h
- configure.ac
- keygen/keygen.c
It's hard to read code where input string arguments use type `char *`, especially if it's cryptographic code. Functions should not modify its input arguments. The compiler can produce better code if it knows the constraints.
Remove code for compatibility with OpenSSL prior to 0.9.8. It's hard to find old versions of OpenSSL. Everybody who cares about security should be using OpenSSL 1.0.2 or newer. But let's allow for older OpenSSL for systems that backport security fixes.
> Use constant strings for input arguments in keygen, kill dead code

- common/arch.h
Without this patch, a warning is printed for every file: https://kojipkgs.fedoraproject.org/packages/xrdp/0.9.1/2.fc26/data/logs/aarch64/build.log
> aarch64 doesn't require pointers to be aligned

- common/ssl_calls.c
- common/ssl_calls.h
- common/trans.c
- common/trans.h
- common/xrdp_client_info.h
- docs/man/xrdp.ini.5.in
- libxrdp/xrdp_rdp.c
- libxrdp/xrdp_sec.c
- xrdp/xrdp.ini
SSL/TLS protocols only listed in ssl_protocols should be used.
The name "ssl_protocols" comes from nginx.
Resolves #428.
Document hasn't been updated yet.
> TLS: new method to specify SSL/TLS version

- .gitmodules
The librfxcodec branch was unset (defaulting to master). The libpainter branch was set to devel. Neither is a good choice for both devel and master branches of xrdp. Use `branch = .` - it's a brand new feature of git: https://github.com/git/git/commit/c8386962d6590ec6f71f353bc5b1b573b1e71b16
At this point it's more documentation than configuration. Submodule updates are made rarely and manually. Still, it's good to document the parent branch and treat both submodules the same way.
> Update submodules to devel branches

- configure.ac
Change help messages to clarify that both libraries are included. Move
messages next to each other. Remove duplicate XRDP_PAINTER conditional.
> Enable painter and librfxcodec by default

- libxrdp/Makefile.am
xrdp_rdp.c includes openssl/ssl.h now, make sure the OpenSSL include path
is used.
---
That's a compile issue, let's merge it before 0.9.2.
> Fix compilation on MacOS

- Makefile.am
- configure.ac
Rather than guess user's intention based on whether --prefix was
specified, use an explicit option to enable strict GNU Coding Standards
for installation directories.
The default is to use /etc and /var rather than corresponding directories
under prefix.
Use --enable-strict-locations in "make distcheck", it expects all
installed files to be under prefix.
> Add --enable-strict-locations option, describe default in its help text

- sesman/chansrv/chansrv.c
This issue fixes a case when xrdpapi (WTS calls) is used in an unexpected way, there is a case which can lead chansrv to get an api struct which is already removed, then chansrv can crash with segfault.
> chansrv: dvc, check channel exists on get/remove api struct

- xrdp/xrdp.ini
If we recommend xorgxrdp as preferred backend, we should set xorgxrdp as default.
This is a part of "Merge Debian local patches project".
> Propel xorgxrdp as default backend, give xorgxrdp the first place

- common/Makefile.am
- common/file_loc.h
- common/os_calls.c
- configure.ac
- docs/man/Makefile.am
- docs/man/xrdp-chansrv.8.in
- docs/man/xrdp-dis.1.in
- sesman/Makefile.am
- sesman/chansrv/Makefile.am
- sesman/chansrv/pulse/module-xrdp-sink.c
- sesman/chansrv/pulse/module-xrdp-source.c
- sesman/session.c
- sesman/sessvc/sessvc.c
- sesman/tools/Makefile.am
- sesman/tools/dis.c
- xorg/X11R7.6/rdp/rdp.h
- xorg/X11R7.6/rdp/rdpmain.c
- xorg/X11R7.6/rdp/rdpmisc.c
- xorg/X11R7.6/rdp/rdpup.c
- xrdp/Makefile.am
- xrdpapi/Makefile.am
- xrdpapi/xrdpapi.c
The default remains `/tmp/.xrdp` for compatibility with older versions of X1rdp and xorgxrdp.
The socket directory is configured by passing `--with-socketdir=DIR` to `configure`.
xrdp-sesman passes the socket directory to the backends as XRDP_SOCKET_PATH environment variable. X11rdp uses it.
`file_loc.h` has been striped of the defines that should not have a default value.
Remove cleanup code in xrdp-sessvc, it is obsolete. xrdp-chansrv should be able to clean up after itself.
> Make socket directory configurable

- sesman/chansrv/pulse/module-xrdp-sink.c
- sesman/chansrv/pulse/module-xrdp-source.c
Pulse module doesn't build after recent socket directory change.  This is not a complete fix. One more thing needs to be done. `XRDP_SOCKET_PATH`  needs to be passed pulse module.
> pulse fixes after socket directory change

- sesman/env.c
which is used to store login name. The login name shall be the string
that would be returned by the getlogin() function [1]. Some applications
only refers LOGNAME environment variable and don't fallback to other
variables such as USER.
Fixes #725.  Reported by @seidler2547.
[1] The Single UNIX Specification, Issue 7
> sesman: LOGNAME should be set to username

- sesman/chansrv/pulse/Makefile
The build should be integrated to xrdp and socket directory should be inherited from xrdp but let's apply workaround for the present.
This helps users such as #723.
> pulse: define default socket directory in Makefile

- common/os_calls.c
- Changes made only in the os_calls.c file (keep the libcommon interface intact)
- Exported functions changed: g_tcp_bind g_tcp_bind_address g_tcp_connect
- Support three network configurations:
1) Normal network, with IPv6
2) Partly disabled IPv6 via sysctl.conf
3) Total disabled IPv6 via grub
Please see #714
> Fix to handle OS disabled IPv6, issue #714.

- sesman/startwm.sh
Since /etc/X11/xdm/Xsession calls user's login shell, startwm.sh
should not execute the psuedo code; It causes to execute
~/.profile twice.
> startwm.sh: do not call pseudo shell code for /etc/X11/xdm/Xsession

- common/ssl_calls.c
The non TLS send / recv return 0 on socket close, tls_read / write should too.
> common: ssl_tls_write / read return 0 on socket close

- sesman/env.c
which is used to store login name. The login name shall be the string
that would be returned by the getlogin() function [1]. Some applications
only refers LOGNAME environment variable and don't fallback to other
variables such as USER.
Fixes #725.  Reported by @seidler2547.
[1] The Single UNIX Specification, Issue 7
----
I think this should be shipped to v0.9 stable branch.
> sesman: LOGNAME should be set to username (v0.9)

- .gitignore
- common/xrdp_sockets.h
- sesman/chansrv/pulse/Makefile
- sesman/chansrv/pulse/module-xrdp-sink.c
- sesman/chansrv/pulse/module-xrdp-source.c
- sesman/env.c
* pass xrdp socket path to user session (chansrv) via environment variable
* respect XRDP_SOCKET_PATH environment variable 
* other minor changes
I confirmed this properly works with non-default socket directory. Compiled `--with-socket-dir=/tmp/.xrdp2` option. If this is OK to merge, let's ship this to v0.9 branch too.
> make audio sockets path configurable

- configure.ac
painter and librfxcodec are enabled by default. --disable-* options
disables them.
Before:
--disable-painter       Use included painter library (default: yes)
--disable-rfxcodec      Use included librfxcodec library (default: yes)
After:
--disable-painter       Do not use included painter library (default: no)
--disable-rfxcodec      Do not use included librfxcodec library (default:
no)
----
CC: @proski
> configure: fix confusing help text about painter and librfxcodec

- common/os_calls.c
- common/os_calls.h
- libxrdp/xrdp_iso.c
- libxrdp/xrdp_rdp.c
We shouldn't assume that xrdp daemon is running under root privilege.
In many cases, root privilege is not really needed for xrdp daemon.
xrdp may fail to load certificate/privkey due to lack of permissions
when running under user privilege. Checking existence of files is not
enough and xrdp should output user-friendly log in such case.
Reported by Debian user in bug 856436 [1].
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856436
> Log user-friendly message when certificate/privkey is inaccessible

- sesman/Makefile.am
- sesman/reconnectwm.sh
as it was undocumented and few people know reconnectwm.sh is executed on
client reconnect. The behaviour of startwm.sh / reconnectwm.sh  should
be documented. This is a first step of documenting them.
> sesman: install empty reconnectwm.sh as a template

- sesman/sesman.c
- xrdp/xrdp.c
- xrdp/xrdp.h
- xrdp/xrdp_listen.c
Pointed out by @cocoon in #644.
xrdp and xrdp-sesman should exit with failure status if 3389/tcp or 3350/tcp port is already in use.
Before this fix, as described in #644, `systemd start xrdp` does not show any errors when daemon failed to start due to port already in use.  xrdp and xrdp-sesman executed in foreground should exit with failure status as well.
Tested on FreeBSD 11-STABLE and CentOS 7.  I describe test procedure on CentOS 7.
Use X11RDP-RH-Matic to build xrdp.
First of all, install xrdp from my branch.
```
$ GH_ACCOUNT=metalefty GH_BRANCH=error-used-port ./X11RDP-RH-Matic.sh --nox11rdp
```
Make 3389/tcp in use by another process.
```
$ nc -l 3389 &
$ netstat -an | egrep "3389|3350"
tcp        0      0 0.0.0.0:3389            0.0.0.0:*               LISTEN
tcp6       0      0 …
```
> exit with failure status if port already in use

- docs/man/xrdp-chansrv.8.in
- sesman/chansrv/chansrv.c
since xrdp-chansrv may be run multiple instances per user. For example,
Xvnc backend creates one session per screen geometry.
> chansrv: include display number in chansrv log filename

- common/ssl_calls.c
Describe the situation clearer.
Increase log level since unavailability of ssl protocols defined in config file
may weaken security and it is important for users.
> Reword messages and change log level in ssl_get_protocols_from_string()

- sesman/libscp/libscp_v1s_mng.c
- sesman/scp_v1_mng.c
Test case:  On a system running xrdp with no sessions running run:
xrdp-sesadmin -u=<user> -p=<password> -c=list
Expected result: "No sessions." (ignoring debug output)
Observed result: "Error getting session list."
In the SCP_SERVER_STATE_MNG_LISTREQ case in scp_v1_mng_process() if
there are no sessions it ends the scp session, which causes an error in
the client.  In commit 0017081d the client was changed to report errors,
giving the result above.
Fix by calling scp_v1s_mng_list_sessions() from scp_v1_mng_process()
even when there are no sessions, and if so sending a packet with a count
of zero so that the client gets what it expects.
> xrdp-sesadmin: fix error when there are no sessions

- xrdp/xrdp_mm.c
Should fix #755.
----
I tested these 4 scenario works fine (no disconnection, copy & paste works).
Now clipboard is working fine with Windows 7 mstsc, MS Remote Desktop for Mac 8.0.40 (Build 27310) however not working with FreeRDP due to FreeRDP/FreeRDP#3309.
1. Xvnc backend + clipboard sharing **enabled** client side
2. Xvnc backend + clipboard sharing **disabled** client side
3. vnc-proxy + clipboard sharing **enabled** client side
4. vnc-proxy + clipboard sharing **disabled** client side
> Fix Xvnc backend disconnects when some data copied to clipboard

- common/os_calls.c
Pointed out by: andrecbarros
Closes: #803
> common: fix a glitch with IPv4 struct initialization

- common/os_calls.c
- common/os_calls.h
- sesman/env.c
- sesman/sesman.c
This does 2 things.  The first is use ```g_create_path``` instead of ```g_create_dir``` to ensure the entire path is present when creating the socket path.  The second is to rename ```g_mk_temp_dir``` to something more meaningful.  It is now called ```g_mk_socket_path```.
> Adjustments to XRDP_SOCKET_PATH make process

- common/os_calls.c
append a / to ensure the full path is created even when the config variable lacks a trailing /
> Make the create path a bit more robust

- xrdp/xrdp_listen.c
_(If the "port" specified in /etc/xrdp/xrdp.ini is an absolute path then a
Unix Domain Socket (UDS) is created instead of a TCP port. I want to use
this feature to implement authentication over SSH, issue #773.)_
If you run xrdp with a Unix Domain Socket (UDS) for the port specified in
/etc/xrdp/xrdp.ini then only root can connect to it.
Test case:
1. Edit /etc/xrdp/xrdp.ini to set "port=/var/run/xrdp-local.socket".
2. Restart xrdp.
3. Run the following, as a non-root user.
socat TCP-LISTEN:12345 UNIX-CONNECT:/var/run/xrdp-local.socket &
rdesktop localhost:12345
Expected behaviour: rdesktop starts up and displays the logon dialog.
Observed behaviour: rdesktop exits with "ERROR: Connection closed" and
socat exits with "Permission denied".  (But it suceeds if root runs
socat.)
UDS files are …
> UDS connection only accessible by root

- sesman/Makefile.am
- sesman/verify_user_pam.c
as some operating system such as FreeBSD searches not only `/etc/pam.d`
but also `/usr/local/etc/pam.d` [1].
[1] https://www.freebsd.org/cgi/man.cgi?query=pam.d&sektion=5
> sesman: search pam files also in ${sysconfdir}/pam.d

- sesman/chansrv/chansrv_fuse.c
Running xrdp 0.9.2 on CentOS/RHEL 7.3, we occasionally see coredumps of chansrv, always when logging in.
Investigation of these coredumps shows a SEGV in `xfuse_create_share()`, where the new xinode is inserted into the inode_table. At this point, `g_xrdp_fs` is uninitialized so it seems that `xfuse_init()` has not yet been called.
```
(gdb) print g_xrdp_fs
$1 = {inode_table = 0x0, max_entries = 0, num_entries = 1, next_node = 1}
```
This patch caters for this situation by creating the inode table if required during `xfuse_create_share()`
My local testing shows chansrv to be more robust with this patch. Is there maybe a preferable way to handle this situation, like calling `xfuse_init()` from elsewhere?
> xfuse_create_share() called before xfuse_init()

- instfiles/Makefile.am
Solves #848.
Pointed out by: Fuminobu TAKEYAMA (@ftake)
> instfiles: don't include generated *.services files to distribution

- xrdp/xrdp_login_wnd.c
because ls_logo_filename accepts full path.
See also #776.
> xrdp: accept full path for ls_background_image

- .travis.yml
since Ubuntu Precise (12.04) is retired September 2017. Now build test
is run on Ubuntu Trusty (14.04). A trivial fix for requisite packages
needed.
> travis: Unbreak travis build

- sesman/session.c
- sesman/session.h
Solves #812 and #830.
I'm not sure if pulse module can delete sockets by itself so deleting sockets on session exit.
> sesman: delete socket files when session exits

- xrdp/xrdp_wm.c
fix black screen if hidelogwindow=yes
https://github.com/neutrinolabs/xrdp/issues/414
> fix misuse of hidelogwindow

- xrdp/xrdp_mm.c
This fixes #894
access_control() does not read the port from the configuration file and it uses a hardcoded port instead.
So,  in case we use another port which is not the default one(3350), we are going to fail while connecting.
> xrdp: get port from configfile in access_control()

- common/os_calls.c
Sorry, I always forget to use `g_*` functions defined in `os_calls.c`.
> common: prevent raw use of snprintf

- common/log.c
- common/log.h
TRACE means more verbose than DEBUG. syslog doesn't have more verbose
level than DEBUG, map TRACE to DEBUG for syslog.
> log: add log level TRACE

- xrdpapi/xrdp-ssh-agent.c
Add xrdp-ssh-agent.c which forwards ssh-agent protocol over an RDP
dynamic virtual channel, just as the normal ssh-agent forwards it over
an SSH channel.
Usage:
Run an RDP client with the corresponding plugin enabled; for example
"xfreerdp /ssh-agent ...".
In the remote desktop session run xrdp-ssh-agent and evaluate the output
in the shell as for ssh-agent to set the required environment variables
(specifically $SSH_AUTH_SOCK):
eval "$(xrdp-ssh-agent -s)"
This is the same as for the normal ssh-agent.  You would typically do
this in your Xsession or /etc/xrdp/startwm.sh.
Limitations:
1. Error checking and handling could be improved.
2. This stays running when the xrdp session closes.  This should be
fixed using a command line argument as for the real ssh-agent.
3. This is only tested on …
> Forward ssh-agent data between ssh clients and RDP

- sesman/chansrv/sound.c
Fixes #910, if both client and server support more than one codecs,
g_bbuf_size might be set to wrong value.
There might be a better fix but this certainly fixes the issue.
> sound: g_bbuf_size should be determined after codec is determined

- common/xrdp_constants.h
I added constants' origin AFAIK as I suggested in #947. Still WIP.
Dones:
* Add comments where the constants come from
* seperate RDP origin constants and xrdp constants
Not dones:
* sync names used in the original document
* ~~seperate RDP origin constants and xrdp constants~~
> common: add references to constants' origin

- common/xrdp_constants.h
- libxrdp/xrdp_caps.c
- libxrdp/xrdp_sec.c
Define capset constants in hex as MS-RDPBCGR does. Easier to compare with MS documents.
> Constify color depth and capability set

- neutrinordp/xrdp-neutrinordp.c
workaround for corrupted display like black bars left of cmd with W2K8
as requested here: https://github.com/neutrinolabs/xrdp/issues/860
But maybe someone can do proper fixes.
BTW:
I reported this looong timea go ;)
here:
http://xrdp-devel.766250.n3.nabble.com/Xrdp-devel-NeutrinoRDP-black-lines-with-ping-in-a-remote-console-screenshot-td4025274.html
or here:
https://github.com/neutrinolabs/NeutrinoRDP/issues/1
BTW2: still open bugs:
- ~~misuse of hidelogwindow instead of correct own hideloginwindow~~
- ~~xrdp systemd setting User=root and fix neutrinordp https://github.com/neutrinolabs/NeutrinoRDP/blob/devel/libfreerdp-utils/file.c#L81
(question is if it can cause any harm if home is set to / if it can't get from env)~~
- new cursor + Windows 10
> workaround for corrupted display with W2K8

- sesman/config.c
- sesman/config.h
- sesman/session.c
The new names are used in prototype declaration of this function.
```C
int
env_set_user(const char *username, char **passwd_file, int display,
const struct list *env_names, const struct list *env_values);
```
> [refactor] change unclear variable name 

- libxrdp/xrdp_sec.c
- xrdp/xrdp_mm.c
- xrdp/xrdp_wm.c
In most cases, checking fd > 0 is not valid. open(2) returns -1 on
error, 0 on stdin, 1 on stdout, 2 on stderr, >2 . The border should be
between -1 and 0. Additionally, between 2 and 3.
Pointed out by: #919
> fix potential fd leak

- configure.ac
- mc/Makefile.am
- vnc/Makefile.am
- xup/Makefile.am
The *-module* prevents Mac OS' toolchain from creating *.dylib* files, for xrdp to work on Mac OS these files are needed. This will fix issue #790
> Make changes to generate dylibs in mac again

- sesman/session.c
Pull request #650 is not valid to avoid run session twice.
It certainly stops running session twice but causes #1016.
In FreeBSD, sesman process will run like this. The intermediate
sesman is needed to detect session termination correctly.
```
xrdp-sesman (daemon)
|
+- xrdp-sesman (FreeBSD specific intermediate sesman)
|
+- xrdp-sesman (bsd sesion leader & each session)
|
+- Xorg
+- startwm.sh
+- xrdp-chansrv
```
To stop runninng session twice correctly, just exit before the
intermediate sesman executes Xorg, WM and chansrv.
> FreeBSD: rework setsid code

- instfiles/Makefile.am
- instfiles/pam.d/Makefile.am
- instfiles/pam.d/mkpamrules
- instfiles/pam.d/xrdp-sesman.macos
Mac OS supports PAM, so it makes sense to add support for it, at least I can login after this commit (there are more issues down the line, but this commit fixes that).
Some notes:
* I'm not sure at all if the file */etc/pam.d/authorization* is unique to Mac OS, but it seems to be standard for it (is available in both machines I use)
* The PAM configuration file I uploaded (*xrdp-sesman.macos*) is basically the same as Mac OS' default SSH's PAM configuration, I don't know how to fine tune it but it makes sense you need the same permissions as SSH
> Added PAM support for Mac OS

- .gitignore
- sesman/Makefile.am
- sesman/sesman.ini.in
- xrdp/Makefile.am
- xrdp/xrdp.ini.in
Mac OS needs libraries to be `.dylib` instead of `.so`. By using the same logic available in _docs/man/Makefile.am_ this commit makes the _xrdp/xrdp.ini_ file to depend on the operating system and replace the libraries extensions where necessary
> Make xrdp.ini to be dynamic for each operating system

- common/file.c
- common/ssl_calls.c
> Do not treat `!` as a comment out symbol

- common/ssl_calls.c
until make it possible to use generated DH parameters per installation.
speidy concern about using static DH parameters:
https://github.com/neutrinolabs/xrdp/commit/1690950cc89220366a4dea0495a6948b2f248c33#r27897446
> common: temporarily disable DHE

- common/ssl_calls.c
OpenSSL 1.1.0 makes many structs opaque now, so we can't set its values directly anymore.
Also:
- fix memory leak introduced by PR #1024 in `get_dh2236()`.
- move `SSL_CTX` object creation check to its right place. use `log_message` for logging.
> ssl_calls: support OpenSSL 1.1.0 API for setting DH params

- sesman/chansrv/devredir.c
Sorry about that. I should have been careful.   After reverting this commit, drive redirection works again. This should be shipped to v0.9.6.
----
This reverts commit 5daa09171e1e6e65a1a3ab969775fdf8affffc37.
Causes "double free":
```
[1271363627]: DEV_REDIR  dev_redir_proc_device_iocompletion: 738 : entered: IoStatus=0x0 CompletionId=1
[1271363627]: DEV_REDIR  dev_redir_proc_device_iocompletion: 839 : got CID_DIRECTORY_CONTROL
[1271363627]: DEV_REDIR  dev_redir_proc_query_dir_response: 933 : processing FILE_DIRECTORY_INFORMATION structs
[1271363627]: DEV_REDIR  dev_redir_proc_query_dir_response: 968 : FileName:          .
[1271363627]: DEV_REDIR  devredir_fuse_data_peek: 1335 : returning 0x7f2a9c013410
*** Error in `/usr/sbin/xrdp-chansrv': double free or corruption (out): …
```
> Revert "devredir: fix xinode leak"

- configure.ac
- instfiles/pam.d/Makefile.am
- instfiles/pam.d/mkpamrules
- instfiles/pam.d/xrdp-sesman.arch
system-auth didn't work for gnome under arch linux. 
According to https://wiki.archlinux.org/index.php/PAM#PAM_base-stack system-remote-login seemed to be the right choice. Works for gnome at least.
> instfiles: Add pam.d config for arch linux.

- common/arch.h
In common/arch.h, the endianness detection considers all powerpc
architectures as big endian. Since that is not true for ppc64el, I
added a verification that checks other preprocessor macros, only for
ppc cases.
Signed-off-by: Fernando Seiti Furusato <ferseiti@gmail.com>
> Corrected endianness detection on ppc64el.

- common/ssl_calls.c
- common/ssl_calls.h
- xrdp/xrdp.c
- xrdp/xrdp.h
If multiple versions of OpenSSL installed to the system, it is helpful to know which OpenSSL xrdp uses in case OpenSSL have vulnerability. Also, some cleanups and improvements.
* add OpenSSL version to --version
* use GitHub URL rather than xrdp.org, it should be more helpful
* exit with error code when unknown CLI option given
* show which CLI option is unknown to xrdp
```
$ xrdp --version
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Version 0.9.5
``` 
```
$ xrdp --version
xrdp 0.9.6
A Remote Desktop Protocol Server.
Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
See https://github.com/neutrinolabs/xrdp for more information.
Compiled with OpenSSL 1.0.2o  27 Mar 2018
```
```
$ xrdp --help …
```
> Show OpenSSL version to --version

- docs/man/xrdp.ini.5.in
> docs: '!' is no longer a comment out symbol

- sesman/sesman.ini.in
As reported in #1106, Arch Linux looks to me like using Xorg wrapper now.
> sesman: Update Xorg help comment for Arch Linux

- sesman/tools/sesrun.c
Support sesrun to start different session based on session_code argument, like `sesrun <server> <username> <password> <width> <height> <bpp> <session_cod>`.
Session code 0 for Xvnc, 10 for X11RDP, 20 for Xorg.
> sesrun support start other session based on session_code argument

- configure.ac
This change prints yes or no to configure summary introduced in #1118.
```
$ ./configure --prefix=/usr/local
xrdp will be compiled with:
mp3lame         no
opus            no
fdkaac          no
jpeg            no
turbo jpeg      no
rfxcodec        yes
painter         yes
pixman          no
fuse            no
ipv6            no
vsock           no
pam             yes
kerberos        no
debug           no
strict_locations        no
prefix                  /usr/local
exec_prefix             ${prefix}
libdir                  ${exec_prefix}/lib
bindir                  ${exec_prefix}/bin
sysconfdir              /etc
```
```
$ ./configure --prefix=/usr/local --enable-strict-locations
xrdp will be compiled with:
mp3lame         no
opus            no
fdkaac          no
jpeg            no
turbo jpeg …
```
> configure: set default value for enable_strict_locations

- common/ssl_calls.c
If the SSL object's read_ahead flag is set, it is possible for no more bytes to be readable from the underlying BIO (because OpenSSL has already read them) and for SSL_pending() to return 0, even though readable application data bytes are available (because the data is in unprocessed buffered records).
In this case, ssl_tls_can_recv() return 0 and xrdp will not read the data.
https://www.openssl.org/docs/man1.1.0/ssl/SSL_pending.html
> fix issue #1112: set SSL object's read_ahead flag to be 0

- sesman/config.c
- sesman/config.h
- sesman/sesman.c
As the Debian patch[1] expresses, spitting messages on the console when a process starts in background is a bad idea.
* don't print sesman config summary and any other messages
* create config_dump() function rather than dumping config while config reading
* config_dump() when xrdp-sesman runs in foreground
* remove prototype declaration which no longer exists 
* adjust indent of sesman configuration summary
Logging configuration summary is still dumped on the console. I'll remove it later.
[1] https://salsa.debian.org/debian-remote-team/xrdp/blob/2751ad4d62b1f63dbc2e4b8fa1580fa54b0f5460/debian/patches/shutup-daemon.diff
```
starting sesman...
sesman config:
ListenAddress:            127.0.0.1
ListenPort:               3350
EnableUserWindowManager:  1
UserWindowManager:        startwm.sh …
```
> Dont spit on the console (sesman)

- sesman/scp_v0.c
- sesman/session.c
- sesman/session.h
In some environments, the reconnect script can benefit from access to environment variables set during the PAM session creation. For example, in a Kerberos-based environment, the reconnect script will need KRB5CCNAME to be set to make use of network services.
> Copy the PAM session environment for the reconnect script

- sesman/config.c
We should free this too, right? It is malloc'ed char pointer.
> sesman: fix leak in struct config_sesman

- docs/man/Makefile.am
- docs/man/sesman.ini.5.in
- sesman/config.c
- sesman/config.h
- sesman/sesman.ini.in
- sesman/session.c
Also, 
* make path of reconnectwm.sh configurable
* improve documents 
Solves #1143. Inspired by Fedora's patch[1].
[1] https://src.fedoraproject.org/cgit/rpms/xrdp.git/commit/xrdp-0.9.6-scripts-libexec.patch?id=02f845c1b8cea781313cf3e9efcd6d7d50341824
> Accept full path for DefaultWindowManager

- sesman/chansrv/chansrv.c
- sesman/chansrv/xcommon.c
- sesman/chansrv/xcommon.h
A couple of our guys log out of their remote sessions every night, rather than simply disconnecting and reconnecting.
I'd had reports that when this is done, the chansrv process can exit without unmounting the FUSE filesystem. When the user logs in again, the FUSE system cannot be mounted over the old one so the user loses remote drives and copy-paste.
Since this is fairly common, I attached a debugger to chansrv and set a breakpoint on _exit. Here's what I got (CentOS 7.4):-
```
#0  0x00007f7a1d8df4f0 in _exit () from /lib64/libc.so.6
#1  0x00007f7a1d858a2b in __run_exit_handlers () from /lib64/libc.so.6
#2  0x00007f7a1d858ab5 in exit () from /lib64/libc.so.6
#3  0x00007f7a1de65ee5 in _XDefaultIOError () from /lib64/libX11.so.6
#4  0x00007f7a1de6611e in _XIOError () from …
```
> Add atexit() handler to unmount the filesystem on fatal X error

- sesman/chansrv/pulse/Makefile
This PR fixes https://github.com/neutrinolabs/xrdp/issues/1181 where the Pulseaudio Chanserv module for xrdp fails to compile due to "missing config.h" on Ubuntu 18.04.
This is caused by incorrect spacing between the `-I` parameter and argument to `cc` in the Makefile.
> Corrected spacing between arguments to `cc` for Pulse chansrv Makefile

- xrdp/xrdp.ini.in
- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_types.h
Configured ls_label_width and ls_input_width currently only apply to the combo label and dropdown. Other labels and inputs (username, password, port, ...) use hardcoded defaults.
Also had to change the default label width; for the previous value of 60, "username" ends up just a few pixels too wide.
> xrdp: Use configured values instead of hardcoded ones in login_wnd inputs.

- sesman/chansrv/chansrv_fuse.c
In xfuse_create_file_in_xrdp_fs insure that xfuse_fs is properly initialized.
> Fix crash of xrdp-chansrv process, issue #1202.

- common/xrdp_client_info.h
- common/xrdp_constants.h
- libxrdp/xrdp_caps.c
- libxrdp/xrdp_sec.c
- neutrinordp/xrdp-neutrinordp.c
I'm trying to connect xrdp with Microsoft Remote Desktop for Mac 8(8.0.30030),
Nothing displayed after logged in with neutrinordp-any.This is the output:
```
lfreerdp_context_new: 0x1fae370
loaded module 'libxrdpneutrinordp.so' ok, interface size 408984, version 3
lfreerdp_pre_connect:
The colormap is all NULL
Railsupport !!!!!!!!!!!!!!!!!!
host 10.10.xx.xx port 3389
connected to 10.10.xx.xx:3389
null server certificate
lxrdp_connect: freerdp_connect returned 1
...
```
I think remote_app should not been enable if INFO_RAIL is not set.
MS-RDPERP 3.3.5.1.3 and 3.3.5.1.4
> neutrinordp: don't enable remote_app if the INFO_RAIL flag is not set

- sesman/chansrv/chansrv_fuse.c
First time I connect, I get remote drives as expected in ~/thinclient_drives :- 
```
$ ls ~/thinclient_drives/
J:  P:  R:  S:  T:  U:
```
If I disconnect and reconnect immediately, these drives get duplicated, according to ls:- 
```
$ ls ~/thinclient_drives/
J:  J:  P:  P:  R:  R:  S:  S:  T:  T:  U:  U:
```
Interestingly this duplication is not visible in the GNOME file manager on CentOS.
I've had a look at the code, and it seems the duplication is happening as the fuse inode cache is never cleared. When the user reconnects, the shared drives are being set up again in the fuse inode cache.
If the user reconnects with the same drives, the only visible effect is the drive letter duplication. If however the user reconnects from a differently configured Windows client, the drives may have …
> Reconnecting to session causes duplicate drive entries in fuse fs

- common/trans.c
- xrdp/xrdp_mm.c
Annoying when xrdp does not kill with friendly kill command.  This is better method until we have a connection complete callback in trans.
> xrdp: check term event for more responsive shutdown

- sesman/config.c
Changes in #1147 had a bug. Fixes #1315.
Reported by:    Daniel Hoffend
> sesman: Fix default_wm and reconnect_sh refer wrong path after SIGHUP

- sesman/config.c
Really small potential tidy-up I just spotted.
Following commit 81703c426f8498022c28a231df7d88ca28bfa842, there are
no longer any references to g_cfg from within sesman/config.c, and so the
`extern` reference can be removed, reducing the coupling between these two files.
> Remove unnecessary reference from sesman/config.c

- sesman/chansrv/irp.h
Fixes #1335.
```
In file included from ./irp.h:27:
./chansrv_fuse.h:39:5: error: unknown type name 'time_t'
time_t          atime;             /* Time of last access.              */
^
./chansrv_fuse.h:40:5: error: unknown type name 'time_t'
time_t          mtime;             /* Time of last modification.        */
^
./chansrv_fuse.h:41:5: error: unknown type name 'time_t'
time_t          ctime;             /* Time of last status change.       */
^
3 errors generated.
*** Error code 1
```
> Fix build after #1327

- sesman/chansrv/sound.c
When playing long audio, audio can fall behind.  This uses the acks to keep it close.
> chansrv: don't let audio fall behind

- xrdp/xrdp_mm.c
For some reasons, sometimes xrdp get stuck while connecting chansrv.  Even if all channels are disabled by config (allow_channels=false), xrdp try to connect to chansrv. This doesn't fix chansrv connecting issue but at least xrdp need not to connect to chansrv at all when no channels enabled.
See also: #1288
> xrdp: skip connecting to chansrv when no channels enabled

- instfiles/pam.d/mkpamrules
Please see the details in https://lists.opensuse.org/opensuse-factory/2019-08/msg00113.html. The old directory for probing the pam configuration file is also kept for backward compatibility reason.
> mkpamrules: Support openSUSE's usage of /usr/etc/pam.d to contain the pam configuration files.

- xrdp/xrdp_listen.c
[linux/vm_sockets.h](https://github.com/torvalds/linux/blob/v5.3/include/uapi/linux/vm_sockets.h) defines `VMADDR_CID_ANY` and `VMADDR_PORT_ANY` (both
equal to `-1U`) for vsock cid and port respectively. This change aims to
add the capability to parse negative cid and port numbers for vsock from
the config and pass them to the kernel.
Allows for valid configurations such as `port=vsock://-1:3389` to be
correctly processed, but will parse port and cid inputs like `---1` to
`-`, which should currently get silently turned into 0 by `atoi` inside
`g_sck_vsock_bind_address`. Inputs that do not contain `-` get parsed as
by `xrdp_listen_parse_integer`.
Addresses #1403
> make vsock config accept -1 for cid and port

- xrdp/xrdp.c
> xrdp: do not exit when caught SIGHUP

- docs/man/sesman.ini.5.in
- sesman/chansrv/Makefile.am
- sesman/chansrv/chansrv.c
- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/chansrv_fuse.h
- sesman/chansrv/chansrv_xfs.c
- sesman/chansrv/chansrv_xfs.h
- sesman/chansrv/devredir.c
- sesman/chansrv/devredir.h
- sesman/chansrv/irp.c
- sesman/chansrv/irp.h
- sesman/chansrv/ms-erref.h
- sesman/chansrv/ms-fscc.h
- sesman/chansrv/ms-rdpefs.h
- sesman/chansrv/ms-smb2.h
- sesman/chansrv/smartcard.c
- sesman/sesman.ini.in
- Reimplemented inode store in separate module `chansrv_xfs.[hc]`
- Allowed atimes and mtimes to be written to Windows side
- Mapped directory/file user write bit to (inverted) Windows FILE_ATTRIBUTE_READONLY bit
- Mapped file user execute bit to Windows FILE_ATTRIBUTE_SYSTEM bit
- Implemented improved security for remotely mounted drives (see man sesman.ini)
- Implemented USB device removal, allowing hot-plug/remove of memory sticks
- Fixed `pagefile.sys` (etc) breaking Ubuntu file browser
- Fixed write offset bug
- Allowed renaming of open files
- Improved reported error codes
- Fixed various memory leaks
- Removed hardcoded buffer sizes where appropriate
- Addressed valgrind/memcheck errors related to struct fuse_file_info pointers.
This improves the remote filesystem support to a …
> Significant remote file system improvements

- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/chansrv_fuse.h
Added includes for C/POSIX types referenced in chansrv_fuse.h to chansrv_fuse.h
Fixes #1461
> Include file tidy-up

- xrdpvr/xrdpvr.c
[xrdpvr/xrdpvr.c:918] -> [xrdpvr/xrdpvr.c:926]: (warning) Identical condition 'rv==0', second condition is always false
> xrdpvr/xrdpvr.c: remove redundant condition

- sesman/chansrv/chansrv_fuse.c
sesman/chansrv/chansrv_fuse.c:1719:9: error: Memory pointed to by 'full_path' is freed twice. [doubleFree]
> sesman/chansrv/chansrv_fuse.c: resolve double free found by cppcheck

- common/os_calls.c
unless flushing stream before exitting, `xrdp --version | cat` will
show empty output.
Fixes #1471.
Actually, I'm not sure why `_exit()` is called in `g_exit()` instead of `exit()`.
@jsorg71 can you review if `g_deinit()` is a fair place to flush stream?
CC: @matt335672 I'd appreciate if you also have a look at this.
> common: flush stream in g_deinit()

- .cirrus.yml
some tests are failing due to FreeBSD OpenSSL version change.
> FreeBSD CI: simplify CI test for a while

- xrdp/xrdp_cache.c
This PR addresses the cppcheck warning generated by cppcheck for `xrdp/xrdp_cache.c` mentioned in #1473 
The `COMPARE_WITH_CRC32()` macro checks both its pointer arguments against NULL. cppcheck takes this as an indicator that either of the pointers could be NULL, and generates the warning accordingly against the 'bitmap' local variable
This variable cannot actually be NULL, and so the check performed by the macro is not needed.
In this case, the warning does not indicate an actual bug.
> xrdp_cache: Fix cppcheck 1.89+1.90 warnings

- sesman/chansrv/chansrv_xfs.c
It's possible for xfs (g_xfs) to be null due to fuse mounts failing.
If g_xfs is null chansrv will crash with sig. fault.
> Use g_free for xfs/g_xfs in xfs_delete_xfs_fs

- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/devredir.c
This PR addresses the cppcheck warning generated by cppcheck for `xrdp/xrdp_{xfs,fuse}.c` and `devredir.c` mentioned in #1473
The warning in `chansrv_fuse.c` generated by cppcheck 1.90 (but not 1.89 or 1.82) appears to be a regression in cppcheck which has already been reported - see cppcheck TRAC [9292](https://trac.cppcheck.net/ticket/9292) and [9437](https://trac.cppcheck.net/ticket/9437). Following a `realloc()` failure, a `free()` of the original region results in a false positive.
cppcheck allows for false positives to be flagged with specially formed comments. The `--inline-suppr` command-line flag is needed to enable these. This approach has been taken for this file.
The warning in `devredir.c` appears to be valid code used to generate a random number if `/dev/urandom` is …
> chansrv-fuse Fix cppcheck 1.89+1.90 warnings

- .travis.yml
- scripts/install_cppcheck.sh
- scripts/run_cppcheck.sh
Adds a Travis CI job to run cppcheck automatically.
Since the default version of cppcheck used by the xenial image on Travis is fairly old (1.72), this PR downloads a later version of cppcheck and builds it before running it on XRDP. AFAICT travis-ci does not support a better way to do this currently - see travis-ci/travis-ci#1734. This obviously adds time to the check, but it's not enormous. My last run of this job on Travis took 3-and-a-half minutes.
The scripts used to download and run cppcheck are designed to be used by developers without needing to invoke travis-ci. TI can document this in the Wiki.
The version of cppcheck used is parameterized in `.travis.yml` so it can be easily updated.
**Edit 4/3/20:** Following the merge of #1481 and #1485, the CI job for this PR succeeds.
> Add cppcheck to travis-ci

- sesman/sesman.ini.in
It has been moved: https://www.archlinux.org/packages/extra/x86_64/xorg-server/
Fixes: #1448
> Fix Xorg path for Arch Linux

- instfiles/pam.d/mkpamrules
- instfiles/pam.d/xrdp-sesman.system
- instfiles/pam.d/xrdp-sesman.unix
Slackware recently acquired a pam package, which can be used with XRDP.
This PR adds an old-style PAM definition for sesman using `pam_unix.so`. This definition is now installed, if suitable, with `make install` and if no better definitions are found. The definition would work on other systems than Slackware.
The `mkpamrules` script has been tidied up slightly, while staying Bourne shell compatible. It will now fail if it can't install a usable PAM definition rather than installing something unusable.
This PR addresses half of the concerns raised in #1558
> Support Slackware with pam

- common/ms-rdpbcgr.h
- sesman/chansrv/chansrv.c
- sesman/chansrv/smartcard_pcsc.c
- xrdp/xrdp_bitmap.c
Here's a better attempt to replace #1551 
Fixes  #1533, fixes #1534, fixes #1544
#1533 - Checked the supported strings for the group parameter (see here). They're all relatively small, so code restructured to just allow a short string here, and check for it.
#1534 - Similarly the allowed string for a virtual channel name is quite small here - see here.
#1544 - Checked for integer overflow explicitly when requesting buffer.
I've not attempted to change the argument to g_malloc() to an unsigned integer here - I think that needs more thought and a separate PR
> Check for overflow before g_malloc() calls

- common/trans.c
- libxrdp/libxrdp.c
- libxrdp/xrdp_iso.c
This PR addresses a couple of OOB accesses raised by @hac425xxx and contains a number of other fixes.
- `trans_force_read_s()` The max size check does not need to be part of the read loop. This change moves the check out of the loop and uses a macro from `parse.h` to do it.
- `libxrdp_force_read()` Error messages improved, plus fixed another possible unreported OOB if a length of 1-3 was passed in the TKTP header.
- `xrdp_iso_process_rdp_neg_req()` Added check that the stream contains the rest of the RDP_NEG_REQ ([MS-RDPCGR](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPBCGR/%5bMS-RDPBCGR%5d.pdf) 2.2.1.1.1) before reading it.
- `xrdp_iso_recv_msg()` Added function header explaining purpose of function (took me a while to figure it out). Added check that …
> Address possible memory out-of-bounds accesses on connect requests

- libxrdp/xrdp_caps.c
Fixes #1569 
rdesktop 1.9.0 (as delivered with Ubuntu 20.04) sends a TS_MULTIFRAGMENTUPDATE_CAPABILITYSET structure ([MS-RDPBCGR] 2.2.7.2.6) with a MaxRequestSize of 65535.
If the user has disabled fastpath output using `use_fastpath` in `xrdp.ini`, the following happens:-
- An output buffer is created of size 32768 in `xrdp_orders_create()`.
- Receipt of TS_MULTIFRAGMENTUPDATE_CAPABILITYSET in `xrdp_caps_process_multifragmentupdate()` sets `client_info.max_fastpath_frag_bytes` to 65535.
- This value is used by `xrdp_orders_check()` va the `MAX_ORDERS_SIZE` macro to determine when to send the orders buffer. Consequently the buffer overflows when being written to.
This PR simply ignores any sent `MaxRequestSize` value if fastpath output is disabled.
> Ignore TS_MULTIFRAGMENTUPDATE_CAPABILITYSET from client if fp disabled

- libxrdp/libxrdp.c
- libxrdp/libxrdpinc.h
- libxrdp/xrdp_fastpath.c
- libxrdp/xrdp_mcs.c
A server reset is used to implement  a client resize.
Currently this is done by sending a TS_DEACTIVATE_ALL_PDU and then resending capabilities with TS_DEMAND_ACTIVE_PDU by `libxrdp_reset()`
It's possible at the moment for channel data to be read from chansrv and sent to the RDP client between these two messages. This is because at the end of `xrdp_mcs_send()` for the 'deactivate all' we call `xrdp_mcs_call_callback()`. If there's pending chansrv data it's sent to the client.
This appears to be at odds with [MS-RDPBCGR 3.2.5.5.1](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/e3dddf9e-ddc7-4622-a0d4-cc1d68f1f1ac) which calls for the client to disable all its input handlers.
This is also what FreeRDP 2.0.0 appears to do. If a message is received between …
> Prevent chansrv input channels being scanned during a server reset

- docs/man/sesman.ini.5.in
- docs/man/xrdp.ini.5.in
- libxrdp/libxrdp.c
- sesman/session.c
- sesman/tools/sesrun.c
- vnc/vnc.c
- vnc/vnc.h
- xrdp/xrdp.ini.in
- xrdp/xrdp_mm.c
This has been discussed in the past - see #259 and #287.
The VNC backend still seems to be with us, and still seems to have a few useful use cases.  At our place, developers working at home are are using Citrix to connect in to a Windows farm and from there are using XRDP to connect to the Linux workstations. Some of them have reported noticeably better performance using Xvnc rather than Xorg in this configuration.
This PR supports the VNC resizing and multi-screen features used by tigervnc.  I've tested both resizing and multi-screen on CentOS 7.5 (tigervnc 1.8). and resizing on xubuntu 18.04 (tigervnc 1.7).  I can't currently test multi-monitor on xubuntu due to a lack of kit.
I've made the feature optional to avoid breaking workflows used by existing users. So by default there's no …
> Add resizeable backend VNC support

- .travis.yml
- common/log.c
- common/os_calls.c
- common/pixman-region.c
- scripts/install_cppcheck.sh
This PR adds support for the recently-released cppcheck 2.1.
There are two commits - one to support cppcheck 2.x and one to address the additional warnings generated by this utility.
cppcheck 2.1 has an additional dependency on z3 which is apparently [highly recommended](https://sourceforge.net/p/cppcheck/news/2020/05/cppcheck-20/), but I have no more details on exactly what it does. In any case, this is supported here.
The cppcheck code expects a header file `z3_version.h` which is not present in the Xenial distro used by travis. A function `create_z3_version_h()` has been added to the install cppcheck to create this file in the cppcheck external directory if it is not available.
Running cppcheck 2.1 on the existing devel branch generates the following output:-
```
Cppcheck 2.1
Command: …
```
> Cppcheck 2.1

- sesman/libscp/libscp_v0.c
- sesman/libscp/libscp_v1s.c
- sesman/libscp/libscp_v1s_mng.c
Fix errors identified by Travis CI in PR for above CVE.
In all cases where a tui32 has been replaced by an int, the read value is followed by a bounds check for both less-than or greater-than, so no unsigned overflows have been introduced by this change
> Fixed CVE-2020-4044 CI errors

- .travis.yml
- common/pixman-region.c
- configure.ac
- mc/mc.h
- sesman/access.c
- sesman/scp_v1.c
- sesman/scp_v1_mng.c
This pull request fixes the build errors that occur when xrdp is built with --enable-xrdpdebug and CFLAGS=-Werror -Wall. This pull request also configures the build to use -Werror -Wall as the default CFLAGS for make when run on a developer's machine or on the build servers.
This issue was debugged by @matt335672 in https://github.com/neutrinolabs/xrdp/pull/1633#issuecomment-660892330 and this change should prevent this issue from affecting other developers.
> Fixing the build with --enable-xrdpdebug and CFLAGS=-Werror -Wall

- common/xrdp_client_info.h
- common/xrdp_constants.h
- libxrdp/xrdp_sec.c
- neutrinordp/xrdp-neutrinordp.h
- sesman/verify_user_pam.c
- xup/xup.c
- xup/xup.h
The MS docs state that the maximum length of a username/password/domain etc is 511. xrdp checks for this but it's internal buffers are 256. This makes it into a define and sets the maximum size to 512 (null terminator needs to be counted)
Fixes: #1648
> Fix buffer len for client info

- sesman/sesman.ini.in
Related to VNC resizing #1343.
Although I'd updated the manpage, I'd missed the actual comment for Policy= in sesman.ini
> Updated sesman.ini comment for Policy= in line with the manpage

- libxrdp/xrdp_channel.c
Problem:
The data chunk buffer is allocated based on the total length field in a DYNVC_DATA_FIRST message. Upon receiving subsequent DYNVC_DATA messages, the data payload is appended to the chunk buffer without first checking that there is enough space remaining in the chunk buffer. This could lead to a buffer overrun in the server.
Solution:
This pull request adds a check to verify that the chunk buffer has enough remaining space to accept the received payload, and returns an error if there is not enough space in the buffer.
> Adding checks to prevent buffer overruns during data chunk re-assembly

- common/log.c
Compiling the current development wavefront on Ubuntu 20.04 (gcc 9.3.0) results in the following errors:-
```
log.c: In function ‘log_message’:
log.c:558:30: error: ‘%.2d’ directive output may be truncated writing between 2 and 11 bytes into a region of size between 9 and 16 [-Werror=format-truncation=]
558 |     snprintf(buff, 21, "[%.4d%.2d%.2d-%.2d:%.2d:%.2d] ", now->tm_year + 1900,
|                              ^~~~
log.c:558:24: note: directive argument in the range [-2147483647, 2147483647]
558 |     snprintf(buff, 21, "[%.4d%.2d%.2d-%.2d:%.2d:%.2d] ", now->tm_year + 1900,
|                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
from log.c:28:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output …
```
> Fixed compiler warnings/errors about snprintf truncations in log.c

- docs/man/xrdp-chansrv.8.in
- sesman/chansrv/Makefile.am
- sesman/chansrv/chansrv.c
- sesman/chansrv/chansrv_config.c
- sesman/chansrv/chansrv_config.h
- sesman/chansrv/chansrv_fuse.c
- sesman/chansrv/clipboard.c
- sesman/session.c
This pull request:-
- Creates a config module for chansrv similar to the one in sesman.
- adds an optional -c (or --config) option to chansrv to allow the path to `sesman.ini` to be specified.
- removes the `CHANSRV_RESTRICT_OUTBOUND_CLIPBOARD` environment variable used between sesman and chansrv to pass `RestrictOutboundClipboard` over - it's now read directly from the config file.
This is one of three PRs to implement #1588. This one does not depend on the other two and has two other uses:-
1. It could be easily expanded to read chansrv logging parameters from sesman.ini (See #1633) 
2. Removing `CHANSRV_RESTRICT_OUTBOUND_CLIPBOARD`  allows for a manual chansrv restart process to be implemented as follows:-
- unmount ~/thinclient_drives if mounted.
- Run chansrv directly from the …
> chansrv improved config support

- SECURITY.md
- common/os_calls.c
- common/os_calls.h
- common/xrdp_client_info.h
- docs/man/xrdp.ini.5.in
- libxrdp/xrdp_rdp.c
- libxrdp/xrdp_sec.c
- xrdp/xrdp.ini.in
- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_types.h
This feature allows to embed a token in the username field. Tokens
are separated from the username by the ASCII field separator character
0x1F (unicode 0x001F).
See https://github.com/neutrinolabs/xrdp/issues/1667
cc @metalefty @matt335672
> Add support for token authentication

- .travis.yml
Follow up for #1659 to add a CI build using the Ubuntu Focal platform version of the gcc compiler and dependencies.
This pull request depends on compiler error fixes in #1659 being merged.
* should all CI builds be updated to use the latest platform/compiler versions? Or should one/most builds use the older platform version to verify that xrdp continutes to build on the older platform?
* add/upgrade a clang build to the latest version
> Adding a Travis CI build using Ubuntu Focal

- genkeymap/genkeymap.c
The conflict on the size of xfree86_to_evdev between genkeymap.c and
evdev-map.c is causing build failures in openSUSE builds
> genkeymap: Fix an array declaration conflict

- common/log.c
- docs/man/xrdp.8.in
- libxrdp/libxrdp.c
- libxrdp/libxrdpinc.h
- libxrdp/xrdp_rdp.c
- xrdp/xrdp.c
- xrdp/xrdp.h
- xrdp/xrdp_listen.c
- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_process.c
- xrdp/xrdp_types.h
- xrdp/xrdp_wm.c
This is the third and last PR in a series to implement #1588  (separate config file for xrdp and sesman).
The other two are for sesman (#1650) and chansrv (#1635), and are largely independent of this PR. This PR affects xrdp and libxrdp.
This PR makes the following changes:-
Opened the .ini file read-only with `g_file_open_ex` rather than `g_file_open`. Without this change, the logging code creates an empty ini file if one wasn't present, which is probably not what is required!
- A few methods were made static where not required to be global
- File run through astyle which found a few issues.
- A few hard-coded string value sizes have been removed.
- local variable `no_daemon` replaced with `daemon` to avoid double-negatives (i.e. `!no_daemon`)
- Manpage updated
- Other changes made to …
> Added -c /--config option to xrdp

- sesman/startwm.sh
SUSE distributions are switched to use /usr/etc for system configuration, Xsession startup files is involved.
https://lists.opensuse.org/opensuse-factory/2019-08/msg00113.html
> startwm.sh: Additionally support /usr/etc/X11/xdm/Xsession

- docs/man/xrdp.ini.5.in
- xrdp/xrdp.ini.in
As discussed in #1610, updated the man to clarify that the address property is no longer supported and warn users that interfaces MUST be UP for xrdp to correctly start.
> Updated man and .ini file regarding address:port parameters.

- .github/workflows/build.yml
This pull request reduces the build time of xrdp in github actions by about 2min 30sec per build by caching the cppcheck build artifacts. Caching the cppcheck build artifacts is safe because cppcheck is a a dependency and the workflow always builds cppcheck from a git tag from the cppcheck repo.
This caching is a 10% reduction in build time across all builds (current build time is approx. 21min CPU time)
Example builds:
* without caching: https://github.com/neutrinolabs/xrdp/runs/1428776621
* with caching cppcheck build output: https://github.com/aquesnel/xrdp/runs/1440410754
> Add caching of cppcheck to github action CI builds

- common/log.c
- common/log.h
- sesman/tools/sesadmin.c
This is a bit of tidy-up work for the standalone utilities in `sesman/tools`.
These utilities call library functions which use the logging facility.  Since they're utilities, they don't really need to log anywhere other than the current console. This change adds a function `log_config_init_for_console()` to the logging sub-system which allows this to be done in a straightforward manner.
The utility `sesadmin` has been modified to use the new facility.
Other changes to log.c:-
- A log file is no longer mandatory.
- A way to disable the logging config dump on startup has been added.
- The logging dump to stdout generates slightly less output for the console and syslog
@aquesnel - if you have the time, I'd be interested in any comments you have as you were the last person to make significant …
> Add log_config_init_for_console() for utilities

- docs/man/xrdp-sesman.8.in
- docs/man/xrdp-sesrun.8.in
- sesman/config.c
- sesman/config.h
- sesman/sesman.c
- sesman/sig.c
- sesman/tools/sesrun.c
This PR is the second of three required to implement #1588 (separate config file for xrdp and sesman).
The first PR is #1635, and this PR depends on that one for correct chansrv operation. The last PR (TBD) is independent of the first two and concerns xrdp only.
This PR makes the following changes:-
- command-line argument parser added which adds common functionality with XRDP (`--help` and `--version` arguments)
- Simplification of `config.c` interface. The `struct config_sesman` is allocated as part of the read, and unnecessary global functions are removed.
- ~~Passes --config on to chansrv when it is started (hence dependency on #1635)~~ (8/9/2020 - no longer needed)
- Manpage updated
- --config argument added here too for completeness.
- Manpage updated (and corrected)
> Add -c/--config option to sesman

- sesman/session.c
There are two points.
Make sure cleanup files happen after chansrv and Xserver exit. If these
child processes lock socket files, the deletion might fail.
Usually, cleanup of xorgxrdp related socket files is handled by
xorgxrdp. Just in case it failed, perform cleanup also in sesman.
Fixes #1740. Thanks to @matt335672.
Sponsored by:   Cybertrust Japan
Sponsored by:   HAW International
> sesman: address the issue of socket file leftovers

- docs/man/sesman.ini.5.in
The ChansrvLogging section name was added and changed in #1633 but this documentation line was missed when renaming the section name.
> Fix typo in sesman.ini man page

- common/defines.h
- libxrdp/libxrdp.c
- libxrdp/libxrdp.h
- libxrdp/xrdp_bitmap32_compress.c
- libxrdp/xrdp_caps.c
- libxrdp/xrdp_channel.c
- libxrdp/xrdp_fastpath.c
- libxrdp/xrdp_iso.c
- libxrdp/xrdp_jpeg_compress.c
- libxrdp/xrdp_mcs.c
- libxrdp/xrdp_mppc_enc.c
- libxrdp/xrdp_orders.c
- libxrdp/xrdp_rdp.c
- libxrdp/xrdp_sec.c
- libxrdp/xrdp_surface.c
Follow-on pull request to #1633 which migrates all logging in the **libxrdp** directory to use the LOG() and LOG_DEVEL() macros.
> Unify logging in libxrdp

- common/log.c
- common/log.h
As part of the logging refactoring in #1708 I broke the code location based log level filtering. This pull request fixes the code location log level filtering.
> Fixing code location log level filtering

- sesman/Makefile.am
- sesman/verify_user.c
- sesman/verify_user_kerberos.c
- sesman/verify_user_pam_userpass.c
This PR is prompted by #1768 
Investigation showed that:-
- some of the auth modules use functions now moved to the new string_calls.h module (see 0a1a8f40e52934718df666e64696e79802802d7e) and the CI doesn't check these.
- The `verify_user_pam_userpass.c` module accessed with `--enable-pamuserpass` could no longer be called. This is a regression introduced with c69a26e9b434a3b68edfb3a3a91086a6e0703cc1 (#1751) which made in compulsory in this instance to also specify `--disable-pam`.
Both of these issues are fixed with this PR.
> Fix regressions in auth modules

- .github/workflows/build.yml
- common/pixman-region.c
- scripts/install_cppcheck.sh
- sesman/chansrv/chansrv_xfs.c
Cppcheck bumped to 2.3.
This version of cppcheck generated additional warnings:-
<details>
<summary>sesman/chansrv/chansrv_xfs.c</summary>
<pre>
sesman/chansrv/chansrv_xfs.c:293:16: error: Null pointer dereference: xfs-&gt;inode_table [nullPointer]
xfs-&gt;inode_table[0] = NULL;
^
sesman/chansrv/chansrv_xfs.c:272:26: note: xfs-&gt;inode_table is assigned value 0
xfs-&gt;inode_table = NULL;
^
sesman/chansrv/chansrv_xfs.c:293:16: note: Null pointer dereference
xfs-&gt;inode_table[0] = NULL;
^
sesman/chansrv/chansrv_xfs.c:294:16: error: Null pointer dereference: xfs-&gt;inode_table [nullPointer]
xfs-&gt;inode_table[FUSE_ROOT_ID] = xino1;
^
sesman/chansrv/chansrv_xfs.c:272:26: note: xfs-&gt;inode_table is assigned value 0
xfs-&gt;inode_table = NULL;
^
sesman/chansrv/chansrv_xfs.c:294:16: …
> Bump cppcheck version to 2.3

- common/ssl_calls.c
- common/ssl_calls.h
Fixes #1776 
At present the certificate chain presented for TLS needs to be RSA. However, current mstsc.exe and Remmina clients can accept ECC certificates if they are presented with them.
xrdp can be made usable with non-RSA certificates and private keys by changing the call to `SSL_CTX_use_RSAPrivateKey_file()` (which only loads RSA keys) to `SSL_CTX_use_PrivateKey_file()` (which loads any private key type). This call has been present in OpenSSL since at least version 0.9.6.
During the course of investigating #1776, it was found that the error logging in `ssl_calls.c` is simply not working. Much of it goes to stdout which is disabled.
There are three commits in this PR:-
1. Move all logging to user the new macros
2. Run the ssl_calls files through `astyle`
3. Replace the call to load …
> Support EC cryptographic keys for TLS

- common/log.c
- common/log.h
- docs/man/xrdp-sesman.8.in
- docs/man/xrdp.8.in
- sesman/sesman.c
- sesman/sig.c
- xrdp/xrdp.c
- xrdp/xrdp_types.h
Here's an initial stab at removing the logging output on stdout by default (see #1762)
It's largely what I suggested in #1762, but :-
- It was easier to retain the `dump_on_start` member and just add a parameter to `log_start()`
- I've also included the config dump which is done by sesman.
- I've also removed an `xrdp-sesman` message "starting sesman in foreground..."
Both `xrdp` and `xrdp-sesman` take a `--log-config` argument which results in the old behaviour.
> Remove output on stdout by default on daemon startup

- docs/man/Makefile.am
- docs/man/sesman.ini.5.in
- docs/man/xrdp-chansrv.8.in
- docs/man/xrdp-genkeymap.8.in
- docs/man/xrdp-sesadmin.8.in
- docs/man/xrdp-sesman.8.in
- docs/man/xrdp-sesrun.8.in
- docs/man/xrdp.8.in
- docs/man/xrdp.ini.5.in
Minor manpage fixes and improvements
- `xrdp`, `xrdp-sesman` and `xrdp-chansrv` are in `$(sbindir)` rather than `$(bindir)`. This change makes that clear in the pages.
- The groff macros `.UR` and `.RE` are used for web urls so that HTML manpages (when we generate them) will work properly.
- The repeated string 'http://www.xrdp.org/' for the xrdp homepage has been replaced with a macro.
Any other suggestions welcome.
> Minor manpage fixes

- libxrdp/libxrdp.c
The `libxrdp_send_bell` function does not follow the MS-RDPBCGR spec for the [TS_PLAY_SOUND_PDU_DATA](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/4c1683b2-3a92-4319-8f7e-2318b3546c02) message.
This pull request reconciles the original author's intent based on their comments with the spec.
This pull request has been tested using the VNC backend since the Xorg backend does not seem to support sending bell messages.
> Fixing TS_PLAY_SOUND_PDU_DATA to set the correct frequency and duration

- common/log.h
- common/ms-rdpbcgr.h
- common/parse.h
- common/xrdp_constants.h
- libxrdp/libxrdp.c
- libxrdp/libxrdp.h
- libxrdp/xrdp_caps.c
- libxrdp/xrdp_channel.c
- libxrdp/xrdp_fastpath.c
- libxrdp/xrdp_iso.c
- libxrdp/xrdp_mcs.c
- libxrdp/xrdp_mppc_enc.c
- libxrdp/xrdp_orders.c
- libxrdp/xrdp_orders_rail.c
- libxrdp/xrdp_rdp.c
- libxrdp/xrdp_sec.c
- sesman/chansrv/chansrv_fuse.c
Follow up pull request from #1738 to add logs with more detailed information to the libxrdp code.
This code conflicts with #1738 and should therefore wait to to be merge until after #1738 
* incorporate feedback changes made in #1738
* update code formatting with astyle
> Add detailed logging to libxrdp

- libxrdp/libxrdp.c
- libxrdp/libxrdpinc.h
- xrdp/xrdp_mm.c
- xrdp/xrdp_wm.c
Fixes #1775 
The particular error focussed on here this :-
```
[yyyymmdd-hh:mm:ss] [ERROR] libxrdp_query_channel - Channel out of range 4
```
Previous to this PR, the only way that xrdp code had to iterate over the channels was to call `libxrdp_query_channel()` with channel ID values increasing from zero until the call failed. This method would always result in the above message being generated when the maximum channel ID was exceeded. Although the message is harmless it is misleading in the sense that no error has actually occured.
The PR adds the call `libxrdp_get_channel_count()` so that code which needs to iterate over the channels can use a `for` loop to do this. This occurs in two places:-
1. `xrdp_mm_trans_send_channel_setup()` iterates over the channels when sending them to …
> Added libxrdp_get_channel_count()

- configure.ac
- xrdp/xrdp_mm.c
This is addressing a minor annoyance of mine.
I had a conversation with @metalefty a while ago about avoiding double negatives where possible (i.e. replace `if (!no_daemon)` with `if (daemon)`) to improve readability for developers whose first language isn't English.
This PR replaces `#ifdef USE_NOPAM` with `#ifdef USE_PAM` in the xrdp daemon code. I have to say that even as a native English speaker I find this one needs a couple of tries to parse in my head.
> Rename USE_NOPAM as USE_PAM

- .cirrus.yml
FreeBSD 12.1 CI builds are currently failing with the following error:-
```
./bootstrap
/usr/local/bin/autoconf
/usr/local/bin/automake
/usr/local/bin/libtool
/usr/local/bin/pkg-config
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
autom4te-2.69: need GNU m4 1.4 or later: /usr/local/bin/gm4
aclocal: error: /usr/local/bin/autom4te-2.69 failed with exit status: 1
autoreconf-2.69: aclocal failed with exit status: 1
```
Installing a FreeBSD 12.1 VM replicates the problem. On further investigation:-
```
$ /usr/local/bin/gm4 --version
m4 (GNU M4) 1.4.18
ld-elf.so.1: /usr/local/bin/gm4: Undefined symbol "fputs_unlocked@FBSD_1.6"
```
The reason is that the FreeBSD packages are provided by major version, and …
> Bump FreeBSD version to 12.2

- xup/xup.c
- xup/xup.h
Follow-on pull request to #1633 which migrates all logging in the xup directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* error logs use the LOG macro
* update code formatting with astyle for all files in xup/*
> Unify logging in xup/*

- xrdp/xrdp.h
- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_mm.c
- xrdp/xrdp_process.c
- xrdp/xrdp_types.h
- xrdp/xrdp_wm.c
Readability change for xrdp_wm.
Currently, a `login_mode` member variable is used to keep track of the state of the login box and connection state. It takes the values 0, 1, 2, 3, 10 and 11.
The PR replaces `login_mode` with `login_state` and changes the values assigned to it as follows:-
Was | Now
---|---
0| WMLS_RESET
1| WMLS_USER_PROMPT
2| WMLS_START_CONNECT
3| WMLS_CONNECT_IN_PROGRESS
10| WMLS_CLEANUP
11| WMLS_INACTIVE
These enumeration constants are documented in xrdp_types.h
> Readability fix for WM states

- common/defines.h
- mc/mc.c
- mc/mc.h
Follow-on pull request to #1633 which migrates all logging in the mc directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* update code formatting with astyle for all files in mc/*
* removed `LIB_DEBUG` since it is no longer used
> Unify logging in mc/*

- neutrinordp/xrdp-color.c
- neutrinordp/xrdp-neutrinordp.c
- neutrinordp/xrdp-neutrinordp.h
Follow-on pull request to #1633 which migrates all logging in the neutrinordp directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* Migrate logging to the LOG() and LOG_DEVEL() macros (using text transform script) 
* error logs use the LOG macro
* update code formatting with astyle for all files in xrdp/*
> Unify logging in neutrinordp/*

- xrdp/lang.c
- xrdp/xrdp.c
- xrdp/xrdp.h
- xrdp/xrdp_bitmap.c
- xrdp/xrdp_cache.c
- xrdp/xrdp_encoder.c
- xrdp/xrdp_font.c
- xrdp/xrdp_listen.c
- xrdp/xrdp_login_wnd.c
- xrdp/xrdp_mm.c
- xrdp/xrdp_painter.c
- xrdp/xrdp_process.c
- xrdp/xrdp_region.c
- xrdp/xrdp_types.h
- xrdp/xrdp_wm.c
Follow-on pull request to #1633 which migrates all logging in the xrdp directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* error logs use the LOG macro 
* add XRDP_BOOT_LOG_LEVEL environment variable to enable run time debugging of xrdp before the logging sub-system is initialized.
* update code formatting with astyle for all files in xrdp/*
> Unify logging in xrdp/*

- xrdpapi/xrdp-ssh-agent.c
- xrdpapi/xrdpapi.c
- xrdpapi/xrdpapi.h
Follow-on pull request to #1633 which migrates all logging in the xrdpapi directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* error logs use the LOG macro
* update code formatting with astyle for all files in xrdp/*
> Unify logging in xrdpapi/*

- vnc/vnc.c
Follow-on pull request to #1633 which migrates all logging in the vnc directory to use the LOG() and LOG_DEVEL() macros.
Changes:
* error logs use the LOG macro
* update code formatting with astyle for all files in xrdp/*
> Unify logging in vnc/*

- .github/workflows/build.yml
This change includes the OS version in the cppcheck cache name for the cppcheck github action.
This ensures that when `ubuntu-latest` is updated, we do not use the old cache - moving from 18.04 to 20.04 broke cppcheck as the symbol `Z3_get_error_msg` was removed from the Z3 library - see https://github.com/Z3Prover/z3/issues/660
> Include OS version in github action cache for cppcheck

- common/xrdp_client_info.h
- libxrdp/xrdp_rdp.c
As discussed in gitter, add a version guard to xrdp_client_info.
There's probably more that can be done here in terms of restructuring this. I notice a lot of the stuff above the line 'Private to xrdp below this line' is not actually used by xorgxrdp. Alternatively, maybe we should split this into two structures so the compiler can pick up differences. Thoughts?
BTW : the include's been run through astyle. All I've actually done is add the 'version' field and the macro and change the comment 'NO CHANGES ABOVE THIS LINE' to the (hopefully) more informative 'Private to xrdp below this line'
> Add versioning to xrdp_client_info

- scripts/install_xrdp_build_dependencies_with_apt.sh
We recently had an issue with 32-bit CI builds, spotted by @aquesnel in #1826.
The linked issue https://github.com/actions/virtual-environments/issues/2917 which was undoubtedly a problem has been resolved, and yet our own builds were still breaking with this particular error from `apt install`:-
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
openjdk-8-jre-headless : Depends: ca-certificates-java but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may …
```
> Remove openssl:i386 from 32-bit builds

- .github/workflows/build.yml
cppcheck 2.4 was released on 2021-03-21.
A quick check showed no code changes are needed on our part to get a clean scan from cppcheck 2.3. Any reason not to upgrade anyone can think of?
> Bumped cppcheck to v2.4

- common/string_calls.c
- common/string_calls.h
- docs/man/xrdp.ini.5.in
- sesman/chansrv/chansrv.c
- sesman/chansrv/pcsc/xrdp_pcsc.c
- sesman/tools/Makefile.am
- sesman/tools/dis.c
- xrdp/xrdp.ini.in
- xrdp/xrdp_mm.c
- xrdpapi/xrdpapi.c
While triaging #1846, I noticed that chansrv won't run if the DISPLAY is :0
This prevents the following use case being possible:-
- User starts console session
- User runs Vino/x11vnc/whatever to expose console session on port 5900 (VNC).
- User runs xrdp-chansrv in console session
- User uses `chansrvport=/path/to/xrdp_chansrv_socket_0`  in `xrdp.ini` to connect to chansrv while connecting to the existing VNC session on port 5900.
This doesn't sound like a bad use-case to me. Am I missing something?
This PR allows chansrv to connect to DISPLAY 0, and also cleans up the function `get_display_num_from_display()`.
Also, shall I add code to `xrdp_mm.c` to default the path to the socks dir, so the user can just specify `xrdp_chansrv_socket_0` rather than needing the socks dir path which is …
> Allow DISPLAY=:0 for chansrv

- tests/memtest/Makefile.am
- tools/devel/tcp_proxy/Makefile.am
These tools shouldn't be delivered to end-users, included in distro
packages. Also the execuable names "memtest" and "tcp_proxy" are too
general to install into sbin dir.
> do not install test & development tool

- README.md
- common/Makefile.am
- common/ms-rdpbcgr.h
- common/ms-rdpedisp.h
- common/xrdp_client_info.h
- libxrdp/xrdp_channel.c
- neutrinordp/xrdp-neutrinordp.c
- neutrinordp/xrdp-neutrinordp.h
- vnc/vnc.c
- vnc/vnc.h
- xrdp/xrdp.h
- xrdp/xrdp.ini.in
- xrdp/xrdp_mm.c
- xrdp/xrdp_types.h
- xup/xup.c
- xup/xup.h
Implements https://github.com/neutrinolabs/xrdp/issues/448
- Based on https://github.com/jsorg71/xrdp/tree/dynamic_monitor
- Tested with xorgxrdp
- Tested with vnc
- Only works with single monitor.
Depends on https://github.com/neutrinolabs/xorgxrdp/pull/183
To test either use Microsoft Remote Desktop (From the Windows or Mac OS app store) and configure to resize the screen or FreeRDP with the `/dynamic-resolution` flag set.
> Resolution switching without reconnecting.

- Makefile.am
- configure.ac
- tests/common/Makefile.am
- tests/memtest/Makefile.am
Fix for pkg-config usage:
* rely on pkg-config when finding check 
* add missing CFLAGS when using check obtained via pkg-config
Adjust unit tests:
* relax dependency checking on check (check is not necessary if unit tests are not run)
* `make distcheck` should only succeed if check is installed
> Relax dependency checking on check and miscellaneous fixes for pkg-config usage

- neutrinordp/xrdp-neutrinordp.c
The leakage does not occur in the most usual use case of xrdp.
It occurs in NeutrinoRDP proxy mode with PAM authentication enabled.
Reported by @TOMATO-ONE
---
Note: It shouldn't be a problem in the most use case of xrdp and it is not a vulnerability such as remote code execution. So I've raised the fix as a usual public PR.
> neutrinordp: avoid pampassword leakage
